/**
 * initiate-paystack-payment — self-contained single-file edge function.
 * Safe to paste directly into the Supabase web console editor.
 * All shared utilities are inlined — no external local imports needed.
 */
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// ─── CORS ────────────────────────────────────────────────────────────────────
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// ─── PHONE NORMALIZATION ──────────────────────────────────────────────────────
// Normalize the contact phone before it enters Paystack metadata so it can never
// later overflow contributions.phone (varchar(20)) at verification/recovery time.
// Keep in sync with kolekto-be-old/utils/normalizePhone.js (authoritative tests).
function normalizePhone(raw: unknown, maxLen = 20): string | null {
  if (raw == null) return null;
  const s = String(raw).trim();
  if (!s) return null;
  const hasPlus = s.startsWith("+");
  const digits = s.replace(/\D/g, "");
  if (!digits) return null;
  let out = (hasPlus ? "+" : "") + digits;
  if (out.length > maxLen) out = out.slice(0, maxLen);
  return out;
}

// ─── SHARED TYPES ─────────────────────────────────────────────────────────────
type FeeBearer = "contributor" | "organizer";

interface TicketSelection {
  tierId: string | null;
  tierName: string;
  pricePerUnit: number;
  quantity: number;
  subtotal: number;
  description?: string | null;
  prefix?: string | null;
  remainingCapacity?: number | null;
}

class PaymentValidationError extends Error {
  status: number;
  code: string;
  logContext?: Record<string, unknown>;
  constructor(
    message: string,
    status = 400,
    code = "payment_validation_error",
    logContext?: Record<string, unknown>
  ) {
    super(message);
    this.name = "PaymentValidationError";
    this.status = status;
    this.code = code;
    this.logContext = logContext;
  }
}

// ─── FINANCIAL PROJECTION ENGINE (delegated) ─────────────────────────────────
//
// Financial math is delegated to the Financial Projection Engine (FPE), inlined
// below as a GENERATED block from the ONE canonical source
// (kolekto-shared-financial/src). Regenerate with `npm run bundle:edge`; never
// hand-edit between the markers. The IIFE isolates the engine's scope so the
// edge-specific helpers below keep their own names with no collisions.
// >>> FPE-ENGINE-INLINE (generated by kolekto-shared-financial/scripts/bundle-edge.mjs — DO NOT EDIT) >>>
// deno-lint-ignore-file
// Canonical source: kolekto-fe-old/kolekto-shared-financial/src — regenerate with `npm run bundle:edge`.
const FPE = (() => {
  // ───────────────────────────── src/types.ts ─────────────────────────────
  /**
   * types.ts — L0 type contracts for the Financial Projection Engine.
   *
   * These are pure type declarations (erased at runtime). They describe the
   * shapes the engine consumes and produces. Every runtime (Node, Deno) shares
   * these definitions; the SQL mirror encodes the same shapes as columns.
   *
   * DESIGN INVARIANT: the engine is a projection. Its inputs are only the two
   * immutable financial event streams — paid `contributions` and `withdrawals`.
   * Everything else (wallets) is derived output, never input.
   */

  /** Who absorbs the platform + gateway fees. */
  type FeeBearer = "contributor" | "organizer";

  /**
   * The collection product types. The engine only branches on these for fee
   * rates and normalization; all other product behaviour lives in the callers.
   */
  type CollectionType =
    | "fixed"
    | "fundraising"
    | "tiered"
    | "ticket"
    | "open_pool";

  /**
   * A single paid contribution row — one of the two sources of truth.
   *
   *   amount       = the NET contribution (the organizer's money; NO fees mixed in)
   *   gross_amount = what the contributor actually paid the gateway (net + fees
   *                  when contributor-borne; equal to net when organizer-borne).
   *                  May be absent/0 on legacy rows → falls back to `amount`.
   *   created_at   = ISO timestamp used to classify settled vs pending at cutoff.
   */
  interface ContributionRow {
    amount: number;
    gross_amount?: number | null;
    created_at?: string | null;
    [key: string]: unknown;
  }

  /**
   * A withdrawal row — the second source of truth. Only `amount` and `status`
   * participate in balance math. Status is matched against the canonical
   * COMPLETED / PENDING sets in constants.ts.
   */
  interface WithdrawalRow {
    amount: number;
    status?: string | null;
    [key: string]: unknown;
  }

  /** Output of `calculateFees`. `totalPayable` is what the contributor is charged. */
  interface FeeBreakdown {
    platformFee: number;
    gatewayFee: number;
    totalFees: number;
    totalPayable: number;
  }

  /**
   * The one wallet shape the engine projects. Enforced invariants (asserted in
   * the conformance suite):
   *   - ledger === available + pending
   *   - available >= 0
   *   - withdrawn <= net (a wallet cannot withdraw more than it ever earned net)
   */
  interface WalletProjection {
    /** Σ gross paid (what contributors handed the gateway). */
    gross: number;
    /** Σ net (Total Raised) — organizer money, fees excluded. */
    net: number;
    /** Σ completed/approved withdrawals. */
    withdrawn: number;
    /** Σ net where created_at >= cutoff (not yet settleable). */
    pending: number;
    /** max(0, settledNet − withdrawn) — the withdrawable-eligible settled money. */
    available: number;
    /** available + pending — total funds still in the wallet. */
    ledger: number;
  }

  /**
   * The legacy Node field names (utils/financial.js#computeWalletBalances).
   * Kept as an explicit shape so the Node adapter and the differential parity
   * suite can compare byte-for-byte against today's backend without any mapping
   * ambiguity. `computeWallet` (the canonical output) is a pure relabelling of
   * these same numbers.
   */
  interface WalletBalancesLegacy {
    netPayment: number;
    grossPayment: number;
    pendingBalance: number;
    availableBalance: number;
    ledgerBalance: number;
    completedWithdrawals: number;
  }

  /** Output of `computeCollectionTotals`. */
  interface CollectionTotals {
    /** Σ net contribution amounts (Total Raised). */
    totalContributions: number;
    /** Count of paid contribution rows. */
    count: number;
  }

  /** Output of `computeWithdrawalEligibility` — the strict withdrawable cap. */
  interface WithdrawalEligibility {
    /** available − Σ pending withdrawal requests, floored at 0. */
    withdrawable: number;
    /** Alias of `withdrawable`; the cap the UI and validator compare against. */
    cap: number;
  }

  /** A price tier as stored on a collection (loose shape — passthrough preserved). */
  interface TierInput {
    id?: string | null;
    name?: string | null;
    price?: number | null;
    quantity?: number | null;
    prefix?: string | null;
    description?: string | null;
    [key: string]: unknown;
  }

  /** Output row of `buildTierAvailability` (input tier + sold/remaining stats). */
  interface TierAvailability extends TierInput {
    tierId: string | null;
    tierName: string;
    tierKey: string;
    sold: number;
    totalCapacity: number | null;
    remainingCapacity: number | null;
  }

  // ───────────────────────────── src/constants.ts ─────────────────────────────
  /**
   * constants.ts — L0 canonical financial constants.
   *
   * THE single source for every rate, cap, hour, and status set in Kolekto's
   * money math. Node and Deno import these; the SQL mirror hard-codes the same
   * literals under `-- MIRRORS kolekto-shared-financial` annotation.
   *
   * Lifted verbatim from the reference implementation (kolekto-be-old
   * utils/financial.js), which reconciliation validates at 0 drift. The ONE
   * deliberate convergence: COMPLETED_WITHDRAWAL_STATUSES adopts the Node set
   * (the superset), resolving the latent Node/Edge divergence documented in
   * FINANCIAL_COMPUTATION_MATRIX.md row 15.
   */


  /**
   * Platform fee rate per collection type.
   *   fundraising → 1%; everything else → 0.5%.
   * Unknown types fall back to PLATFORM_FEE_RATE_DEFAULT (see calculateFees).
   */
  const PLATFORM_FEE_RATES: Readonly<Record<CollectionType, number>> = {
    fundraising: 0.01, // 1%
    fixed: 0.005, // 0.5%
    tiered: 0.005, // 0.5%
    ticket: 0.005, // 0.5%
    open_pool: 0.005, // 0.5%
  };

  /** Fallback platform rate for any collection type not in PLATFORM_FEE_RATES. */
  const PLATFORM_FEE_RATE_DEFAULT = 0.005; // 0.5%

  /** Paystack gateway fee rate — 1.5% for all collection types. */
  const GATEWAY_FEE_RATE = 0.015;

  /** Per-fee cap: each of platform and gateway fee is capped at ₦2,000. */
  const MAX_FEE_AMOUNT = 2000;

  /**
   * T+1 settlement hour, in UTC. Settlement runs at 5:00 AM WAT (UTC+1) = 4:00
   * AM UTC. A payment made before the most recent 04:00 UTC cutoff is settled
   * (available); at/after is pending until the next cutoff.
   */
  const SETTLEMENT_HOUR_UTC = 4;

  /** Milliseconds in one day — the cutoff step. */
  const ONE_DAY_MS = 86_400_000;

  /**
   * Withdrawal statuses that count as money that has LEFT the wallet.
   *
   * CANONICAL (superset). Node accepted all four; Edge accepted only
   * {completed, successful}. The engine adopts Node's set — the value
   * reconciliation already validates at 0 drift. Edge conformance to this set is
   * proven by the "approved"/"success" divergence golden vectors.
   *
   *   completed / successful / success → legacy Paystack-transfer terminal states
   *   approved                         → the state the admin panel writes on a
   *                                      manual payout ("mark as paid")
   */
  const COMPLETED_WITHDRAWAL_STATUSES: ReadonlySet<string> = new Set([
    "completed",
    "successful",
    "success",
    "approved",
  ]);

  /**
   * Withdrawal statuses that are in-flight: they reserve against the withdrawable
   * cap but are NOT yet deducted from `available` (only completed withdrawals
   * reduce available). See computeWithdrawalEligibility.
   */
  const PENDING_WITHDRAWAL_STATUSES: ReadonlySet<string> = new Set([
    "pending",
    "processing",
  ]);

  /** All recognised collection types (for validation / iteration). */
  const COLLECTION_TYPES: readonly CollectionType[] = [
    "fixed",
    "fundraising",
    "tiered",
    "ticket",
    "open_pool",
  ];

  /** The two fee bearers. */
  const FEE_BEARERS: readonly FeeBearer[] = ["contributor", "organizer"];

  /**
   * Aggregate constant bag — the shape design docs refer to as `FPE.CONSTANTS`.
   * Prefer the named exports above in new code; this is a convenience view.
   */
  const CONSTANTS = {
    PLATFORM_FEE_RATES,
    PLATFORM_FEE_RATE_DEFAULT,
    GATEWAY_FEE_RATE,
    MAX_FEE_AMOUNT,
    SETTLEMENT_HOUR_UTC,
    ONE_DAY_MS,
    COMPLETED_WITHDRAWAL_STATUSES,
    PENDING_WITHDRAWAL_STATUSES,
    COLLECTION_TYPES,
    FEE_BEARERS,
  } as const;

  // ───────────────────────────── src/primitives.ts ─────────────────────────────
  /**
   * primitives.ts — L1 pure financial primitives.
   *
   * Deterministic, dependency-free building blocks. No I/O, no Supabase, no
   * fetch, no logging. Time enters ONLY through an explicit `now` parameter
   * (defaulting to `new Date()` so existing call sites behave identically) —
   * there is no hidden `Date.now()` inside the math.
   *
   * Every function here is a verbatim lift of the reference implementation
   * (kolekto-be-old/utils/financial.js), except:
   *   - fee rates / cap / cutoff hour come from constants.ts (one source), and
   *   - `getSettlementCutoff` / `isPaymentSettled` accept an injectable `now`.
   * Behaviour is otherwise byte-identical; the differential parity suite proves
   * it against the live backend file.
   */


  // ---------------------------------------------------------------------------
  // roundCurrency
  // ---------------------------------------------------------------------------

  /**
   * Round to 2 decimal places, coercing non-numeric values to 0.
   *
   * The universal money-rounding primitive: every intermediate and final
   * currency value in the engine passes through this so half-up 2dp behaviour is
   * identical everywhere. (`Number.toFixed` is used exactly as the reference
   * does — matching its rounding to the kobo.)
   */
  function roundCurrency(value: unknown): number {
    return Number((Number(value) || 0).toFixed(2));
  }

  // ---------------------------------------------------------------------------
  // Fee rate lookup
  // ---------------------------------------------------------------------------

  /** Platform rate for a collection type, falling back to the default (0.5%). */
  function platformFeeRate(collectionType: string): number {
    return (
      PLATFORM_FEE_RATES[collectionType as CollectionType] ??
      PLATFORM_FEE_RATE_DEFAULT
    );
  }

  // ---------------------------------------------------------------------------
  // calculateFees
  // ---------------------------------------------------------------------------

  /**
   * Calculate the Kolekto platform fee, Paystack gateway fee, and totals.
   *
   * Rules (unchanged from the reference):
   *   - Fees are ALWAYS calculated on the contribution amount, never on payable.
   *   - contributor-borne → totalPayable = amount + totalFees
   *   - organizer-borne   → totalPayable = amount (fees come out of the net share)
   *   - Each fee is capped at MAX_FEE_AMOUNT (₦2,000) independently.
   *   - Fees are NEVER folded into Total Raised / net.
   */
  function calculateFees(
    amount: number,
    collectionType: string = "fixed",
    feeBearer: FeeBearer = "organizer"
  ): FeeBreakdown {
    const sanitizedAmount = roundCurrency(amount);
    const platformRate = platformFeeRate(collectionType);

    const platformFee = roundCurrency(
      Math.min(sanitizedAmount * platformRate, MAX_FEE_AMOUNT)
    );
    const gatewayFee = roundCurrency(
      Math.min(sanitizedAmount * GATEWAY_FEE_RATE, MAX_FEE_AMOUNT)
    );
    const totalFees = roundCurrency(platformFee + gatewayFee);
    const totalPayable =
      feeBearer === "contributor"
        ? roundCurrency(sanitizedAmount + totalFees)
        : sanitizedAmount;

    return { platformFee, gatewayFee, totalFees, totalPayable };
  }

  // ---------------------------------------------------------------------------
  // deriveNetContribution
  // ---------------------------------------------------------------------------

  /**
   * Given the gross amount a contributor paid and the collection settings,
   * derive the NET contribution amount (what the organizer receives).
   *
   * organizer-borne  → gross === net (fees come out of the organizer's share).
   * contributor-borne → gross = net + platformFee + gatewayFee; back it out.
   *   Estimate net = gross / (1 + platformRate + gatewayRate) (exact when
   *   uncapped), then refine once through calculateFees to absorb the ₦2,000
   *   caps. Verbatim lift of the reference (utils/financial.js).
   */
  function deriveNetContribution(
    grossAmount: number,
    collectionType: string = "fixed",
    feeBearer: FeeBearer = "organizer"
  ): number {
    const gross = roundCurrency(grossAmount);
    if (gross <= 0) return 0;

    if (feeBearer === "contributor") {
      const platformRate = platformFeeRate(collectionType);
      const combinedRate = platformRate + GATEWAY_FEE_RATE;

      // Exact when fees are not capped.
      const estimate = roundCurrency(gross / (1 + combinedRate));

      // Refine once to account for the per-fee caps.
      const { totalFees } = calculateFees(estimate, collectionType, "contributor");
      const refined = roundCurrency(gross - totalFees);

      return Math.max(0, refined);
    }

    // Organizer-borne: gross is the contribution amount.
    return gross;
  }

  // ---------------------------------------------------------------------------
  // normalizeContribution(s)
  // ---------------------------------------------------------------------------

  /**
   * Normalize a single contribution row, correcting legacy rows where
   * `gross_amount` is 0/null by deriving the net amount from the gross.
   *
   *   gross === 0 → row passes through untouched (nothing to derive).
   *   otherwise   → amount := net(gross), gross_amount := gross.
   *
   * organizer-borne  → net = gross − totalFees.
   * contributor-borne → net = deriveNetContribution(gross).
   */
  function normalizeContribution<T extends ContributionRow>(
    row: T,
    feeBearer: FeeBearer = "organizer",
    collectionType: string = "fixed"
  ): T {
    const gross = Number(row.gross_amount || row.amount || 0);
    if (gross === 0) return row;

    const { totalFees } = calculateFees(gross, collectionType, feeBearer);
    const net =
      feeBearer === "organizer"
        ? roundCurrency(gross - totalFees)
        : deriveNetContribution(gross, collectionType, feeBearer);

    return {
      ...row,
      amount: net,
      gross_amount: gross,
    };
  }

  /**
   * Array form of `normalizeContribution` — the exact signature the Node backend
   * uses (`normalizeContributions`). Preserved for drop-in delegation in Wave 1.
   */
  function normalizeContributions<T extends ContributionRow>(
    contributions: T[] | null | undefined,
    feeBearer: FeeBearer = "organizer",
    collectionType: string = "fixed"
  ): T[] {
    return (contributions || []).map((row) =>
      normalizeContribution(row, feeBearer, collectionType)
    );
  }

  // ---------------------------------------------------------------------------
  // T+1 settlement
  // ---------------------------------------------------------------------------

  /**
   * The most recent settlement cutoff at or before `now` — SETTLEMENT_HOUR_UTC
   * (04:00) UTC today, or yesterday's if `now` is before today's cutoff.
   *
   * `now` is injectable (defaults to the real clock) so the cutoff is fully
   * deterministic under test and identical across runtimes given the same input.
   */
  function getSettlementCutoff(now: Date = new Date()): Date {
    const todayCutoff = new Date(
      Date.UTC(
        now.getUTCFullYear(),
        now.getUTCMonth(),
        now.getUTCDate(),
        SETTLEMENT_HOUR_UTC,
        0,
        0,
        0
      )
    );

    return now >= todayCutoff
      ? todayCutoff
      : new Date(todayCutoff.getTime() - ONE_DAY_MS);
  }

  /**
   * True if a payment made at `paymentDate` has settled (was made strictly
   * before the most recent cutoff at `now`). At/after the cutoff → pending.
   */
  function isPaymentSettled(
    paymentDate: Date | string,
    now: Date = new Date()
  ): boolean {
    const cutoff = getSettlementCutoff(now);
    return new Date(paymentDate) < cutoff;
  }

  // ---------------------------------------------------------------------------
  // allocateAmounts
  // ---------------------------------------------------------------------------

  /**
   * Split `total` across `weights`, rounding each share to 2dp and giving the
   * remainder to the last item so the parts always sum EXACTLY back to `total`
   * (no rounding leakage). Verbatim lift of the edge implementation
   * (supabase/functions/_shared/payment.ts).
   *
   *   empty weights            → []
   *   total === 0 or Σweight 0 → all-zero array of the same length
   */
  function allocateAmounts(total: number, weights: number[]): number[] {
    const normalizedWeights = weights.map((weight) =>
      roundCurrency(Math.max(0, weight))
    );
    const sum = normalizedWeights.reduce((acc, weight) => acc + weight, 0);

    if (normalizedWeights.length === 0) return [];
    if (roundCurrency(total) === 0 || sum === 0) {
      return normalizedWeights.map(() => 0);
    }

    let remaining = roundCurrency(total);

    return normalizedWeights.map((weight, index) => {
      if (index === normalizedWeights.length - 1) {
        return remaining;
      }
      const share = roundCurrency((total * weight) / sum);
      remaining = roundCurrency(remaining - share);
      return share;
    });
  }

  // ───────────────────────────── src/projections.ts ─────────────────────────────
  /**
   * projections.ts — L2 pure projections.
   *
   * Take arrays of the two source-of-truth streams (paid contributions,
   * withdrawals) and project derived money: wallet balances, organizer roll-ups,
   * collection totals, tier availability, and the withdrawal cap. Pure and
   * deterministic; time enters only via injected `now`.
   *
   * `computeWalletBalances` is a verbatim lift of the reference
   * (kolekto-be-old/utils/financial.js) with the cutoff made injectable and the
   * completed-withdrawal set sourced from constants. `computeWallet` relabels
   * those same numbers into the canonical WalletProjection shape.
   * `buildTierAvailability` is a verbatim lift of the edge implementation.
   */


  // ---------------------------------------------------------------------------
  // Wallet balance projection (the core)
  // ---------------------------------------------------------------------------

  /**
   * Compute the full wallet balance snapshot from raw paid-contribution and
   * withdrawal rows, in the LEGACY Node field names. This is the byte-for-byte
   * reference shape the differential parity suite compares against the live
   * backend. Prefer `computeWallet` (canonical shape) in new code.
   *
   * @param paidContributions rows with { amount, gross_amount?, created_at }
   * @param withdrawals       rows with { amount, status }
   * @param now               injected clock for the settlement cutoff
   */
  function computeWalletBalances(
    paidContributions: ContributionRow[] | null | undefined,
    withdrawals: WithdrawalRow[] | null | undefined,
    now: Date = new Date()
  ): WalletBalancesLegacy {
    const cutoff = getSettlementCutoff(now);
    const rows = paidContributions || [];

    // Total Raised = Σ net contribution amounts (organizer's money).
    const netPayment = roundCurrency(
      rows.reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );

    // Gross = what contributors actually paid (gross_amount, falling back to
    // amount for legacy rows that never populated the column).
    const grossPayment = roundCurrency(
      rows.reduce(
        (sum, row) => sum + Number(row.gross_amount || row.amount || 0),
        0
      )
    );

    // Pending = net from payments made AT/AFTER the last cutoff (not settleable).
    const pendingBalance = roundCurrency(
      rows
        .filter((row) => {
          const ts = row.created_at ? new Date(row.created_at) : null;
          return ts !== null && ts >= cutoff;
        })
        .reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );

    // Settled = net from payments made BEFORE the cutoff.
    const settledNet = roundCurrency(netPayment - pendingBalance);

    // Completed withdrawals (irreversible) — canonical superset status match.
    const completedWithdrawals = roundCurrency(
      (withdrawals || [])
        .filter((row) =>
          COMPLETED_WITHDRAWAL_STATUSES.has(String(row.status || ""))
        )
        .reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );

    // Available = settled net minus what has already left the wallet (floored 0).
    const availableBalance = roundCurrency(
      Math.max(0, settledNet - completedWithdrawals)
    );

    // Ledger = total funds still in the wallet (pending + available).
    const ledgerBalance = roundCurrency(availableBalance + pendingBalance);

    return {
      netPayment,
      grossPayment,
      pendingBalance,
      availableBalance,
      ledgerBalance,
      completedWithdrawals,
    };
  }

  /**
   * Canonical wallet projection. Same numbers as `computeWalletBalances`,
   * relabelled to the engine's WalletProjection shape:
   *   net → net, gross → gross, pending → pending, available → available,
   *   ledger → ledger, completedWithdrawals → withdrawn.
   *
   * Invariants (asserted in the conformance suite):
   *   ledger === available + pending; available >= 0.
   */
  function computeWallet(
    paidContributions: ContributionRow[] | null | undefined,
    withdrawals: WithdrawalRow[] | null | undefined,
    now: Date = new Date()
  ): WalletProjection {
    const b = computeWalletBalances(paidContributions, withdrawals, now);
    return {
      gross: b.grossPayment,
      net: b.netPayment,
      withdrawn: b.completedWithdrawals,
      pending: b.pendingBalance,
      available: b.availableBalance,
      ledger: b.ledgerBalance,
    };
  }

  // ---------------------------------------------------------------------------
  // Balance selectors (over the canonical projection)
  // ---------------------------------------------------------------------------

  /** Settled, withdrawable-eligible balance. */
  function computeAvailableBalance(
    paidContributions: ContributionRow[] | null | undefined,
    withdrawals: WithdrawalRow[] | null | undefined,
    now: Date = new Date()
  ): number {
    return computeWallet(paidContributions, withdrawals, now).available;
  }

  /** Net from payments not yet past the cutoff. */
  function computePendingBalance(
    paidContributions: ContributionRow[] | null | undefined,
    now: Date = new Date()
  ): number {
    return computeWallet(paidContributions, [], now).pending;
  }

  /** available + pending — total funds still in the wallet. */
  function computeLedgerBalance(
    paidContributions: ContributionRow[] | null | undefined,
    withdrawals: WithdrawalRow[] | null | undefined,
    now: Date = new Date()
  ): number {
    return computeWallet(paidContributions, withdrawals, now).ledger;
  }

  /**
   * Sum the `available` across all of an organizer's wallet projections.
   * Accepts anything carrying a numeric `available` (a WalletProjection or a
   * persisted wallet row exposing `available_balance`).
   */
  function computeOrganizerBalance(
    wallets: Array<{ available?: number; available_balance?: number } | null | undefined>
  ): number {
    return roundCurrency(
      (wallets || []).reduce((sum, w) => {
        if (!w) return sum;
        const available = w.available ?? w.available_balance ?? 0;
        return sum + Number(available || 0);
      }, 0)
    );
  }

  // ---------------------------------------------------------------------------
  // Collection totals
  // ---------------------------------------------------------------------------

  /**
   * Total Raised + paid count for a collection. `totalContributions` is Σ net
   * `amount` (matching Total Raised); `count` is the number of paid rows.
   */
  function computeCollectionTotals(
    contributions: ContributionRow[] | null | undefined
  ): CollectionTotals {
    const rows = contributions || [];
    const totalContributions = roundCurrency(
      rows.reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );
    return { totalContributions, count: rows.length };
  }

  // ---------------------------------------------------------------------------
  // Withdrawal eligibility (strict cap)
  // ---------------------------------------------------------------------------

  /** Σ amounts of in-flight (pending/processing) withdrawal requests. */
  function computePendingWithdrawals(
    withdrawals: WithdrawalRow[] | null | undefined,
    { excludeId = null }: { excludeId?: string | number | null } = {}
  ): number {
    return roundCurrency(
      (withdrawals || [])
        .filter((row) => {
          if (excludeId != null && (row as { id?: unknown }).id === excludeId) {
            return false;
          }
          return PENDING_WITHDRAWAL_STATUSES.has(String(row.status || ""));
        })
        .reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );
  }

  /**
   * The strict withdrawable cap: `available − Σ pending withdrawal requests`,
   * floored at 0. Pending requests reserve against the cap but are NOT deducted
   * from `available` (only completed withdrawals reduce available). This is the
   * ONE number the picker and the request validator compare against.
   *
   * @param wallet             a WalletProjection (or any { available } carrier)
   * @param pendingWithdrawals either a pre-summed number, or the raw withdrawal
   *                           rows (they will be summed over PENDING statuses)
   */
  function computeWithdrawalEligibility(
    wallet: { available: number } | Pick<WalletProjection, "available">,
    pendingWithdrawals: number | WithdrawalRow[]
  ): WithdrawalEligibility {
    const pending =
      typeof pendingWithdrawals === "number"
        ? roundCurrency(pendingWithdrawals)
        : computePendingWithdrawals(pendingWithdrawals);

    const cap = roundCurrency(Math.max(0, Number(wallet.available || 0) - pending));
    return { withdrawable: cap, cap };
  }

  // ---------------------------------------------------------------------------
  // Tier availability (verbatim lift of the edge implementation)
  // ---------------------------------------------------------------------------

  function asNumber(value: unknown): number {
    if (typeof value === "number" && Number.isFinite(value)) return value;
    if (typeof value === "string" && value.trim() !== "") {
      const parsed = Number(value.replace(/,/g, ""));
      if (Number.isFinite(parsed)) return parsed;
    }
    return 0;
  }

  function asPositiveInt(value: unknown): number {
    const parsed = Math.floor(asNumber(value));
    return parsed > 0 ? parsed : 0;
  }

  function getTierMatchKey(tier: TierInput, index: number): string {
    return String(tier.id || tier.name || `tier-${index}`);
  }

  function getTierLabel(tier: TierInput, index: number): string {
    return String(tier.name || `Tier ${index + 1}`);
  }

  function getInfoRows(row: Record<string, unknown>): Array<Record<string, unknown>> {
    if (Array.isArray(row.contributor_information)) {
      return row.contributor_information.filter(
        (entry) => entry && typeof entry === "object"
      ) as Array<Record<string, unknown>>;
    }
    if (row.contact_info && typeof row.contact_info === "object") {
      return [row.contact_info as Record<string, unknown>];
    }
    return [];
  }

  /**
   * Compute sold / remaining capacity per price tier from the paid rows.
   * Verbatim lift of supabase/functions/_shared/payment.ts#buildTierAvailability
   * — matches tiers by TierId then Tier name, sums Quantity (default 1).
   */
  function buildTierAvailability(
    tiers: TierInput[],
    paidRows: Array<Record<string, unknown>>
  ): TierAvailability[] {
    const soldByTier = new Map<string, number>();

    for (const row of paidRows) {
      const infoRows = getInfoRows(row);
      for (const info of infoRows) {
        const tierId = info.TierId ? String(info.TierId) : "";
        const tierName = info.Tier ? String(info.Tier) : "";
        const quantity = asPositiveInt(info.Quantity) || 1;

        if (tierId) {
          soldByTier.set(tierId, (soldByTier.get(tierId) || 0) + quantity);
        } else if (tierName) {
          soldByTier.set(tierName, (soldByTier.get(tierName) || 0) + quantity);
        }
      }
    }

    return tiers.map((tier, index) => {
      const tierId = tier.id ? String(tier.id) : null;
      const tierName = getTierLabel(tier, index);
      const sold =
        (tierId ? soldByTier.get(tierId) : undefined) ||
        soldByTier.get(tierName) ||
        0;
      const totalCapacity = tier.quantity == null ? null : asPositiveInt(tier.quantity);
      const remainingCapacity =
        totalCapacity == null ? null : Math.max(0, totalCapacity - sold);

      return {
        ...tier,
        tierId,
        tierName,
        tierKey: getTierMatchKey(tier, index),
        sold,
        totalCapacity,
        remainingCapacity,
      };
    });
  }

  return { roundCurrency, platformFeeRate, calculateFees, deriveNetContribution, normalizeContribution, normalizeContributions, getSettlementCutoff, isPaymentSettled, allocateAmounts, computeWallet, computeWalletBalances, computeAvailableBalance, computePendingBalance, computeLedgerBalance, computeOrganizerBalance, computeCollectionTotals, computePendingWithdrawals, computeWithdrawalEligibility, buildTierAvailability, PLATFORM_FEE_RATES, PLATFORM_FEE_RATE_DEFAULT, GATEWAY_FEE_RATE, MAX_FEE_AMOUNT, SETTLEMENT_HOUR_UTC, ONE_DAY_MS, COMPLETED_WITHDRAWAL_STATUSES, PENDING_WITHDRAWAL_STATUSES, COLLECTION_TYPES, FEE_BEARERS, CONSTANTS };
})();
// <<< FPE-ENGINE-INLINE <<<

// Bind local names to the engine (byte-identical to the removed hand-written
// versions across all types × bearers × the full amount range — proven by the
// package's edge-differential tests).
const roundCurrency: (value: number) => number = FPE.roundCurrency;
const calculateFees: (amount: number, collectionType: string, feeBearer: FeeBearer) => { platformFee: number; gatewayFee: number; totalFees: number; totalPayable: number } = FPE.calculateFees;
const buildTierAvailability: (tiers: Array<Record<string, unknown>>, paidRows: Array<Record<string, unknown>>) => Array<Record<string, unknown>> = FPE.buildTierAvailability;

function asNumber(value: unknown): number {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value === "string" && value.trim() !== "") {
    const parsed = Number(value.replace(/,/g, ""));
    if (Number.isFinite(parsed)) return parsed;
  }
  return 0;
}

function asPositiveInt(value: unknown): number {
  const parsed = Math.floor(asNumber(value));
  return parsed > 0 ? parsed : 0;
}

function getCollectionType(collection: Record<string, unknown>) {
  return String(collection.collection_type || collection.type || "fixed").trim();
}

function getPriceTiers(collection: Record<string, unknown>) {
  const tiers = collection.price_tiers || collection.pricing_tiers;
  return Array.isArray(tiers) ? tiers : [];
}

// calculateFees and buildTierAvailability are delegated to the engine (bound
// above), byte-identical to the removed hand-written versions. The edge-specific
// getInfoRows / getTierLabel / getTierMatchKey / asPositiveInt helpers are kept
// for matchTier and other local consumers.

function matchTier(
  tiers: Array<Record<string, unknown>>,
  selection: Record<string, unknown>
) {
  const requestedTierId = selection.tierId
    ? String(selection.tierId)
    : selection.id
    ? String(selection.id)
    : null;
  const requestedTierName = selection.tierName
    ? String(selection.tierName)
    : selection.name
    ? String(selection.name)
    : null;

  return (
    tiers.find((tier) => {
      if (requestedTierId && tier.tierId === requestedTierId) return true;
      if (requestedTierName && tier.tierName === requestedTierName) return true;
      return false;
    }) || null
  );
}

function ensureCollectionIsPayable(
  collection: Record<string, unknown>,
  collectionId: string
) {
  const status = String(collection.status || "active");
  if (collection.deleted_at) {
    throw new PaymentValidationError(
      "This collection is no longer available.", 404, "collection_deleted", { collectionId, status }
    );
  }
  if (status === "paused") {
    throw new PaymentValidationError(
      "This collection is currently paused and cannot accept payments.", 400, "collection_paused", { collectionId, status }
    );
  }
  if (status === "closed" || status === "completed") {
    throw new PaymentValidationError(
      "This collection is no longer accepting payments.", 400, "collection_closed", { collectionId, status }
    );
  }
  if (status === "pending_review" || status === "pending_verification") {
    throw new PaymentValidationError(
      "This collection is not available for payment yet.", 400, "collection_unavailable", { collectionId, status }
    );
  }
}

function normalizePaymentRequest(input: {
  collection: Record<string, unknown>;
  metadata: Record<string, unknown>;
  paidRows?: Array<Record<string, unknown>>;
}) {
  const collection = input.collection;
  const metadata = input.metadata || {};
  const paidRows = input.paidRows || [];

  const collectionId = String(
    metadata.collectionId || metadata.collection_id || collection.id || ""
  ).trim();

  if (!collectionId) {
    throw new PaymentValidationError("A valid collection ID is required.", 400, "missing_collection_id");
  }

  ensureCollectionIsPayable(collection, collectionId);

  const collectionType = getCollectionType(collection);

  // CRITICAL: fundraising fees are ALWAYS paid by contributor.
  // This ensures Total Raised = pure contribution amount, fees are separate.
  const feeBearer: FeeBearer =
    collectionType === "fundraising"
      ? "contributor"
      : String(collection.fee_bearer || metadata.feeBearer || "organizer") === "contributor"
      ? "contributor"
      : "organizer";

  const contactSource =
    metadata.contact && typeof metadata.contact === "object"
      ? (metadata.contact as Record<string, unknown>)
      : {};
  const formData =
    metadata.formData && typeof metadata.formData === "object"
      ? (metadata.formData as Record<string, unknown>)
      : {};
  const contact = {
    name: String(contactSource.name || "").trim(),
    email: String(contactSource.email || "").trim(),
    phone: normalizePhone(contactSource.phone) ?? "",
  };

  const allTiers = buildTierAvailability(getPriceTiers(collection), paidRows);
  const maxContributions = asPositiveInt(collection.max_contributions || collection.max_participants);
  const paidCount = paidRows.length;
  const remainingContributionCapacity =
    maxContributions > 0 ? Math.max(0, maxContributions - paidCount) : null;

  let contributionAmount = 0;
  let quantity = 1;
  let selectedTier: string | null = null;
  let selectedTierId: string | null = null;
  let ticketSelections: TicketSelection[] = [];

  if (collectionType === "fundraising" || collectionType === "open_pool") {
    const requestedAmount = roundCurrency(asNumber(metadata.contributionAmount || metadata.amount));
    const minimumAmount = roundCurrency(asNumber(collection.min_contribution || collection.amount));

    if (!requestedAmount || requestedAmount <= 0) {
      throw new PaymentValidationError(
        collectionType === "fundraising" ? "Enter a valid donation amount." : "Enter a valid contribution amount.",
        400, "invalid_amount", { collectionId, collectionType, requestedAmount }
      );
    }
    if (minimumAmount > 0 && requestedAmount < minimumAmount) {
      throw new PaymentValidationError(
        `${collectionType === "fundraising" ? "Minimum donation" : "Minimum contribution"} is NGN ${minimumAmount.toLocaleString("en-NG")}.`,
        400, "amount_below_minimum", { collectionId, requestedAmount, minimumAmount }
      );
    }
    if (remainingContributionCapacity !== null && remainingContributionCapacity < 1) {
      throw new PaymentValidationError(
        "This collection has reached its contribution limit.", 400, "collection_full", { collectionId, paidCount, maxContributions }
      );
    }
    contributionAmount = requestedAmount;

  } else if (collectionType === "ticket") {
    if (String(collection.ticket_mode || "") === "tiered") {
      const rawSelections = Array.isArray(metadata.ticketSelections)
        ? (metadata.ticketSelections as Array<Record<string, unknown>>)
        : [];
      const legacyQuantity = asPositiveInt(metadata.quantity) || 1;
      const legacySelection =
        rawSelections.length === 0 && (metadata.selectedTier || metadata.selectedTierId)
          ? [{ tierId: metadata.selectedTierId, tierName: metadata.selectedTier, quantity: legacyQuantity }]
          : rawSelections;

      if (legacySelection.length === 0) {
        throw new PaymentValidationError(
          "Select at least one ticket tier before checkout.", 400, "missing_ticket_selection", { collectionId }
        );
      }

      ticketSelections = legacySelection
        .map((selection) => {
          const tier = matchTier(allTiers, selection);
          const requestedQuantity = asPositiveInt(selection.quantity);
          if (!tier) {
            throw new PaymentValidationError(
              "One of the selected ticket tiers is no longer available.", 404, "ticket_tier_not_found", { collectionId, selection }
            );
          }
          if (requestedQuantity < 1) return null;
          if (tier.remainingCapacity !== null && requestedQuantity > Number(tier.remainingCapacity)) {
            throw new PaymentValidationError(
              `${tier.tierName} does not have enough tickets left.`,
              400, "insufficient_ticket_capacity",
              { collectionId, tierId: tier.tierId, tierName: tier.tierName, requestedQuantity, remainingCapacity: tier.remainingCapacity }
            );
          }
          return {
            tierId: tier.tierId,
            tierName: tier.tierName,
            pricePerUnit: roundCurrency(asNumber(tier.price)),
            quantity: requestedQuantity,
            subtotal: roundCurrency(asNumber(tier.price) * requestedQuantity),
            description: tier.description ? String(tier.description) : null,
            prefix: tier.prefix ? String(tier.prefix) : null,
            remainingCapacity: tier.remainingCapacity,
          } as TicketSelection;
        })
        .filter(Boolean) as TicketSelection[];

      quantity = ticketSelections.reduce((t, s) => t + s.quantity, 0);
      if (quantity < 1) {
        throw new PaymentValidationError(
          "Select at least one ticket before checkout.", 400, "missing_ticket_quantity", { collectionId }
        );
      }
      contributionAmount = roundCurrency(ticketSelections.reduce((s, sel) => s + sel.subtotal, 0));

    } else {
      quantity = asPositiveInt(metadata.quantity) || 1;
      if (remainingContributionCapacity !== null && quantity > remainingContributionCapacity) {
        throw new PaymentValidationError(
          "Not enough tickets remain for this order.", 400, "insufficient_ticket_capacity",
          { collectionId, quantity, remainingContributionCapacity }
        );
      }
      if (String(collection.allow_multiple_quantity) === "false" && quantity > 1) {
        throw new PaymentValidationError(
          "This ticket only allows one purchase per checkout.", 400, "multiple_quantity_disabled", { collectionId, quantity }
        );
      }
      const unitPrice = roundCurrency(asNumber(collection.amount));
      contributionAmount = roundCurrency(unitPrice * quantity);
      ticketSelections = [{
        tierId: null,
        tierName: String(collection.title || "Ticket"),
        pricePerUnit: unitPrice,
        quantity,
        subtotal: contributionAmount,
        prefix: collection.code_prefix ? String(collection.code_prefix) : null,
        remainingCapacity: remainingContributionCapacity,
      }];
    }

  } else if (collectionType === "tiered") {
    const tier = matchTier(allTiers, {
      tierId: metadata.selectedTierId,
      tierName: metadata.selectedTier,
      name: metadata.selectedTier,
    });
    if (!tier) {
      throw new PaymentValidationError(
        "Select a valid pricing tier before checkout.", 400, "invalid_selected_tier", { collectionId, selectedTier: metadata.selectedTier }
      );
    }
    if (tier.remainingCapacity !== null && Number(tier.remainingCapacity) < 1) {
      throw new PaymentValidationError(
        `${tier.tierName} is sold out.`, 400, "tier_sold_out", { collectionId, tierId: tier.tierId, tierName: tier.tierName }
      );
    }
    contributionAmount = roundCurrency(asNumber(tier.price));
    selectedTier = tier.tierName != null ? String(tier.tierName) : null;
    selectedTierId = tier.tierId != null ? String(tier.tierId) : null;

  } else {
    // fixed (default)
    if (remainingContributionCapacity !== null && remainingContributionCapacity < 1) {
      throw new PaymentValidationError(
        "This collection has reached its contribution limit.", 400, "collection_full", { collectionId, paidCount, maxContributions }
      );
    }
    contributionAmount = roundCurrency(asNumber(collection.amount));
  }

  if (!contributionAmount || contributionAmount <= 0) {
    throw new PaymentValidationError(
      "Unable to determine a valid payment amount for this checkout.",
      400, "invalid_contribution_amount", { collectionId, collectionType, contributionAmount }
    );
  }

  const feeBreakdown = calculateFees(contributionAmount, collectionType, feeBearer);

  return {
    collectionId,
    collectionType,
    collectionTitle: String(collection.title || "Collection"),
    feeBearer,
    contributionAmount,       // ← Total Raised tracks THIS value
    platformFee: feeBreakdown.platformFee,
    gatewayFee: feeBreakdown.gatewayFee,
    totalFees: feeBreakdown.totalFees,
    totalPayable: feeBreakdown.totalPayable,  // ← what Paystack charges
    quantity,
    selectedTier,
    selectedTierId,
    ticketSelections,
    formData,
    contact,
    isAnonymous: Boolean(metadata.isAnonymous),
    codePrefix: String(metadata.codePrefix || collection.code_prefix || "").trim(),
    providedAmount: roundCurrency(asNumber(metadata.totalPayable || metadata.amount || 0)),
  };
}

// ─── MAIN HANDLER ────────────────────────────────────────────────────────────
serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: new Headers(corsHeaders) });
  }

  try {
    const paystackSecretKey = Deno.env.get("PAYSTACK_SECRET_KEY");
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseKey =
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ||
      Deno.env.get("SERVICE_ROLE_KEY") ||
      Deno.env.get("SUPABASE_ANON_KEY");

    console.log("[initiate] env check:", {
      hasPaystackKey: !!paystackSecretKey,
      paystackKeyPrefix: paystackSecretKey ? paystackSecretKey.slice(0, 7) : null,
      hasSupabaseUrl: !!supabaseUrl,
      hasSupabaseKey: !!supabaseKey,
    });

    if (!paystackSecretKey) {
      return new Response(
        JSON.stringify({
          error: "PAYSTACK_SECRET_KEY is not set in Supabase Edge Function secrets.",
          code: "missing_paystack_secret",
        }),
        { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    const keyOk =
      (paystackSecretKey.startsWith("sk_test_") || paystackSecretKey.startsWith("sk_live_")) &&
      paystackSecretKey.length >= 30;

    if (!keyOk) {
      return new Response(
        JSON.stringify({
          error: "PAYSTACK_SECRET_KEY is malformed (must start with sk_test_ or sk_live_).",
          code: "invalid_paystack_secret",
        }),
        { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    if (!supabaseUrl || !supabaseKey) {
      return new Response(
        JSON.stringify({
          error: "Supabase URL or service role key not available inside edge function.",
          code: "missing_supabase_env",
          hasUrl: !!supabaseUrl,
          hasKey: !!supabaseKey,
        }),
        { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    let requestData: Record<string, unknown>;
    try {
      requestData = await req.json();
    } catch {
      return new Response(
        JSON.stringify({ error: "Invalid request body." }),
        { status: 400, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    const { email, metadata, callback_url } = requestData as any;

    if (!email || typeof email !== "string" || !email.includes("@")) {
      return new Response(
        JSON.stringify({ error: "A valid email address is required." }),
        { status: 400, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    if (!metadata || typeof metadata !== "object") {
      return new Response(
        JSON.stringify({ error: "Payment metadata is required." }),
        { status: 400, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    const collectionId = String(
      (metadata as any).collectionId || (metadata as any).collection_id || ""
    ).trim();

    if (!collectionId) {
      return new Response(
        JSON.stringify({ error: "A valid collection is required before checkout." }),
        { status: 400, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    const supabase = createClient(supabaseUrl, supabaseKey);

    // NOTE: do NOT filter on deleted_at here — column may not exist in prod
    // and would fail the whole query. ensureCollectionIsPayable() below
    // checks the deleted_at value on the fetched row if present.
    const { data: collection, error: collectionError } = await supabase
      .from("collections")
      .select("*")
      .eq("id", collectionId)
      .maybeSingle();

    if (collectionError) {
      console.error("[initiate] collection fetch error:", collectionError);
      return new Response(
        JSON.stringify({
          error: `Unable to load collection for checkout: ${collectionError.message}`,
          code: "collection_fetch_failed",
          details: collectionError,
        }),
        { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    if (!collection) {
      return new Response(
        JSON.stringify({ error: "Collection not found. Please check the payment link and try again." }),
        { status: 404, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    const { data: paidRows, error: paidRowsError } = await supabase
      .from("contributions")
      .select("id, amount, contributor_information")
      .eq("collection_id", collectionId)
      .eq("status", "paid");

    if (paidRowsError) {
      console.error("[initiate] paid rows fetch error:", paidRowsError);
      return new Response(
        JSON.stringify({
          error: `Unable to validate collection availability: ${paidRowsError.message}`,
          code: "paid_rows_fetch_failed",
          details: paidRowsError,
        }),
        { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    let normalized: ReturnType<typeof normalizePaymentRequest>;
    try {
      normalized = normalizePaymentRequest({
        collection,
        metadata: metadata as Record<string, unknown>,
        paidRows: (paidRows || []) as Array<Record<string, unknown>>,
      });
    } catch (error: any) {
      if (error instanceof PaymentValidationError) {
        return new Response(
          JSON.stringify({ error: error.message, code: error.code }),
          { status: error.status, headers: { "Content-Type": "application/json", ...corsHeaders } }
        );
      }
      throw error;
    }

    const reference = `kolekto-${Date.now()}-${Math.floor(Math.random() * 1000000)}`;

    // F4: structured payment-lifecycle log (correlation ID = Paystack reference).
    console.log(
      `[initiate ref=${reference}] PAYMENT_INITIATED collectionId=${normalized.collectionId} type=${normalized.collectionType} contributionAmount=${normalized.contributionAmount} totalPayable=${normalized.totalPayable} feeBearer=${normalized.feeBearer} quantity=${normalized.quantity}`
    );

    // Paystack metadata MUST be a simple JSON object. Deeply-nested objects,
    // arrays of objects with many fields, or oversized payloads (> ~5KB) cause
    // Paystack to reject the transaction with a generic "An error occurred" 400.
    //
    // Strategy: keep only primitives at the top level, and serialize any
    // structured data (ticketSelections, formData, contact) into short
    // JSON strings. The verify step parses these back.
    const safeStringify = (value: unknown, maxLen = 1800) => {
      try {
        const s = JSON.stringify(value ?? null);
        return s.length > maxLen ? s.slice(0, maxLen) : s;
      } catch {
        return "null";
      }
    };

    // This object is what actually gets sent to Paystack — it MUST stay flat
    // and capped, per the constraint above. It is never written to our own DB.
    const paystackMetadata: Record<string, unknown> = {
      collectionId: normalized.collectionId,
      collectionType: normalized.collectionType,
      collectionTitle: String(normalized.collectionTitle || "").slice(0, 200),
      contributionAmount: normalized.contributionAmount,
      platformFee: normalized.platformFee,
      gatewayFee: normalized.gatewayFee,
      totalFees: normalized.totalFees,
      totalPayable: normalized.totalPayable,
      feeBearer: normalized.feeBearer,
      selectedTier: normalized.selectedTier || "",
      selectedTierId: normalized.selectedTierId || "",
      quantity: normalized.quantity,
      codePrefix: normalized.codePrefix,
      isAnonymous: normalized.isAnonymous ? 1 : 0,
      contactName: String(normalized.contact?.name || "").slice(0, 120),
      contactEmail: String(normalized.contact?.email || "").slice(0, 120),
      contactPhone: String(normalized.contact?.phone || "").slice(0, 30),
      // Structured fields serialized to strings so metadata stays flat.
      ticketSelectionsJson: safeStringify(normalized.ticketSelections),
      formDataJson: safeStringify(normalized.formData),
      // Paystack renders custom_fields in the receipt UI — optional.
      custom_fields: [
        {
          display_name: "Collection",
          variable_name: "collection_title",
          value: String(normalized.collectionTitle || "").slice(0, 100),
        },
      ],
    };

    // This object is what we persist in OUR OWN database (pending_payment_context,
    // a `jsonb` column with no size limit). It carries the SAME fields as
    // paystackMetadata but with contact/formData/ticketSelections as their real
    // (untruncated) object/array values instead of the JSON-string fields above —
    // reusing paystackMetadata's truncated strings here was a latent bug: a
    // contributor's own answers could be silently cut off in our source-of-truth
    // table, not just in what Paystack receives. verify-paystack-payment's
    // normalizePaymentRequest already prefers these object-shaped fields over the
    // *Json string fallback (see its contactSource/formData handling), so this is
    // a pure upgrade — no verify-side change needed, and every existing row in
    // the old flat shape still parses exactly as before.
    const fullPaymentContext: Record<string, unknown> = {
      ...paystackMetadata,
      contact: normalized.contact,
      formData: normalized.formData,
      ticketSelections: normalized.ticketSelections,
    };

    // D-1: persist the payment context ourselves, keyed by reference, so
    // verification never has to depend solely on Paystack faithfully
    // echoing back the exact metadata object we sent.
    //
    // Persistence is required, not best-effort: a checkout whose context never
    // made it into our DB is exactly the failure mode that left a contributor's
    // submitted answers unrecoverable days later. Retry once to absorb a single
    // transient blip; if it still fails, refuse to start the checkout rather
    // than charge the contributor into a context-less transaction.
    const persistPendingContext = async () =>
      await supabase
        .from("pending_payment_context")
        .insert({
          reference,
          collection_id: normalized.collectionId,
          metadata: fullPaymentContext,
        });

    let contextPersisted = false;
    let lastContextError: string | null = null;
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        const { error: contextError } = await persistPendingContext();
        if (!contextError) {
          contextPersisted = true;
          console.log(`[initiate ref=${reference}] PENDING_CONTEXT_WRITE_OK attempt=${attempt}`);
          break;
        }
        lastContextError = contextError.message;
        console.warn(
          `[initiate ref=${reference}] PENDING_CONTEXT_WRITE_FAILED attempt=${attempt}:`,
          contextError.message
        );
      } catch (contextErr) {
        lastContextError = (contextErr as Error)?.message || String(contextErr);
        console.warn(
          `[initiate ref=${reference}] PENDING_CONTEXT_WRITE_THREW attempt=${attempt}:`,
          lastContextError
        );
      }
      if (attempt === 1) await new Promise((r) => setTimeout(r, 300));
    }

    if (!contextPersisted) {
      // Durable record of the failure — console.warn alone vanishes once this
      // edge function instance recycles, and was the reason a prior
      // double-failure (this write AND Paystack's own metadata echo both
      // failing for the same reference) was invisible until a contributor
      // reported a missing contribution days later.
      try {
        await supabase.from("payment_recovery_log").insert({
          reference,
          collection_id: normalized.collectionId,
          success: false,
          error_code: "pending_context_persist_failed",
          error_message: lastContextError,
          metadata_source: "initiate",
          note: "pending_payment_context insert failed after retry — checkout blocked",
        });
      } catch { /* best-effort logging only; the block below still applies */ }

      return new Response(
        JSON.stringify({
          error: "Unable to initialize payment: failed to persist payment context.",
          code: "payment_context_persist_failed",
        }),
        { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    // F4 diagnostic: metadata size/shape going to Paystack — helps catch
    // truncation-related issues (Paystack has an undocumented practical
    // size limit; oversized metadata can come back malformed) without
    // logging any secret/PII beyond what's already in metadata itself.
    console.log(`[initiate ref=${reference}] METADATA_DIAGNOSTIC`, {
      keys: Object.keys(paystackMetadata),
      totalSize: JSON.stringify(paystackMetadata).length,
      collectionIdPresent: Boolean(paystackMetadata.collectionId),
    });

    console.log("Initiating Paystack payment:", {
      collectionId: normalized.collectionId,
      collectionType: normalized.collectionType,
      contributionAmount: normalized.contributionAmount,
      feeBearer: normalized.feeBearer,
      totalFees: normalized.totalFees,
      totalPayable: normalized.totalPayable,
      reference,
    });

    const paystackUrl = "https://api.paystack.co/transaction/initialize";
    const paystackBody = {
      email,
      amount: Math.round(normalized.totalPayable * 100), // kobo, always totalPayable
      reference,
      callback_url:
        callback_url ||
        `${Deno.env.get("PUBLIC_CALLBACK_URL") || "https://kolekto.vercel.app"}/payment-callback`,
      metadata: paystackMetadata,
    };

    const MAX_RETRIES = 2;
    let lastError: Error | null = null;

    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      try {
        if (attempt > 0) {
          await new Promise((r) => setTimeout(r, 1000 * attempt));
          console.log(`Retry attempt ${attempt}`);
        }

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 25000);

        let paystackResponse: Response;
        try {
          paystackResponse = await fetch(paystackUrl, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${paystackSecretKey}`,
              Accept: "application/json",
            },
            body: JSON.stringify(paystackBody),
            signal: controller.signal,
          });
        } finally {
          clearTimeout(timeoutId);
        }

        console.log("Paystack response:", paystackResponse.status);

        const contentType = paystackResponse.headers.get("Content-Type") || "";

        if (!contentType.includes("application/json")) {
          const text = await paystackResponse.text();
          console.error("Non-JSON Paystack response:", { status: paystackResponse.status, body: text.slice(0, 300) });

          if (paystackResponse.status === 401 || paystackResponse.status === 403) {
            return new Response(
              JSON.stringify({ error: "Payment gateway authentication failed. Check your Paystack secret key in Supabase secrets." }),
              { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
            );
          }

          if (attempt < MAX_RETRIES) { lastError = new Error(`Paystack non-JSON (${paystackResponse.status})`); continue; }

          return new Response(
            JSON.stringify({ error: "Payment gateway returned an unexpected response. Please try again." }),
            { status: 502, headers: { "Content-Type": "application/json", ...corsHeaders } }
          );
        }

        const paystackResult = await paystackResponse.json();

        if (!paystackResponse.ok) {
          // F4: Paystack rejected the initialization
          console.error(
            `[initiate ref=${reference}] PAYSTACK_INIT_FAILED status=${paystackResponse.status}`,
            {
              body: paystackResult,
              sentAmount: paystackBody.amount,
              sentEmail: paystackBody.email,
              metadataKeys: Object.keys(paystackMetadata),
              metadataSize: JSON.stringify(paystackMetadata).length,
            }
          );

          const msg = paystackResult?.message || paystackResult?.error || "Failed to initialize payment";
          if (paystackResponse.status === 401 || paystackResponse.status === 403) {
            return new Response(
              JSON.stringify({
                error: "Payment gateway authentication failed. Check your Paystack secret key in Supabase secrets.",
                code: "paystack_auth_failed",
                paystackStatus: paystackResponse.status,
                paystackBody: paystackResult,
              }),
              { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
            );
          }
          if (attempt < MAX_RETRIES && paystackResponse.status >= 500) { lastError = new Error(msg); continue; }
          // Return Paystack's exact status code so the frontend knows it was a
          // client-side (400) error and can show the real message, not 502.
          return new Response(
            JSON.stringify({
              error: `Paystack: ${msg}`,
              code: "paystack_rejected",
              paystackStatus: paystackResponse.status,
              paystackBody: paystackResult,
            }),
            {
              status: paystackResponse.status >= 400 && paystackResponse.status < 500 ? 400 : 502,
              headers: { "Content-Type": "application/json", ...corsHeaders },
            }
          );
        }

        if (!paystackResult.status) {
          return new Response(
            JSON.stringify({ error: paystackResult?.message || "Failed to initialize payment." }),
            { status: 502, headers: { "Content-Type": "application/json", ...corsHeaders } }
          );
        }

        // F4: Paystack accepted the initialization
        console.log(
          `[initiate ref=${reference}] PAYSTACK_INIT_OK auth_url_present=${!!paystackResult.data?.authorization_url}`
        );

        return new Response(
          JSON.stringify(paystackResult.data),
          { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
        );

      } catch (apiError: any) {
        const isTransient =
          apiError.name === "AbortError" ||
          String(apiError.message).includes("fetch failed") ||
          String(apiError.message).includes("network");

        if (attempt < MAX_RETRIES && isTransient) { lastError = apiError; continue; }

        return new Response(
          JSON.stringify({ error: `Payment gateway connection error: ${apiError.message}` }),
          { status: 502, headers: { "Content-Type": "application/json", ...corsHeaders } }
        );
      }
    }

    return new Response(
      JSON.stringify({
        error: "Payment service is temporarily unavailable. Please try again shortly.",
        details: lastError ? String(lastError) : "All retries exhausted",
      }),
      { status: 502, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );

  } catch (error: any) {
    console.error("[initiate] Unhandled exception:", error?.message, error?.stack);
    return new Response(
      JSON.stringify({
        error: `Unexpected error: ${error?.message || "Unknown error"}`,
        code: "unhandled_exception",
        stack: error?.stack ? String(error.stack).split("\n").slice(0, 5).join("\n") : undefined,
      }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  }
});
