/**
 * verify-paystack-payment — self-contained single-file edge function.
 * Safe to paste directly into the Supabase web console editor.
 * All shared utilities are inlined — no external local imports needed.
 *
 * Fee handling rules (applied to ALL collection types):
 *   - contributionAmount  = base amount (fixed price / selected tier / entered amount)
 *   - totalPayable        = what Paystack charges (contributionAmount + fees if contributor-borne)
 *   - contributions.amount = NET to host:
 *       • feeBearer=contributor → contributionAmount (fees paid on top by contributor)
 *       • feeBearer=organizer   → contributionAmount − fees (fees deducted from payment)
 *   - contributions.gross_amount = what Paystack actually charged the contributor
 *   - fundraising: fees always contributor-borne (override fee_bearer)
 */
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// ─── CORS ─────────────────────────────────────────────────────────────────────
export const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// ─── SHARED TYPES ─────────────────────────────────────────────────────────────
export type FeeBearer = "contributor" | "organizer";

export interface TicketSelection {
  tierId: string | null;
  tierName: string;
  pricePerUnit: number;
  quantity: number;
  subtotal: number;
  description?: string | null;
  prefix?: string | null;
  remainingCapacity?: number | null;
}

export class PaymentValidationError extends Error {
  status: number;
  code: string;
  logContext?: Record<string, unknown>;
  constructor(
    message: string,
    status = 400,
    code = "payment_validation_error",
    logContext?: Record<string, unknown>
  ) {
    super(message);
    this.name = "PaymentValidationError";
    this.status = status;
    this.code = code;
    this.logContext = logContext;
  }
}

// ─── FINANCIAL PROJECTION ENGINE (delegated) ─────────────────────────────────
//
// All financial math is delegated to the Financial Projection Engine (FPE),
// inlined below as a GENERATED block from the ONE canonical source
// (kolekto-shared-financial/src). Regenerate with `npm run bundle:edge`; never
// hand-edit between the markers. The IIFE isolates the engine's scope so the
// edge-specific helpers below (asNumber, tier matching, payment-request
// validation, DB recovery) keep their own names with no collisions.
// >>> FPE-ENGINE-INLINE (generated by kolekto-shared-financial/scripts/bundle-edge.mjs — DO NOT EDIT) >>>
// deno-lint-ignore-file
// Canonical source: kolekto-fe-old/kolekto-shared-financial/src — regenerate with `npm run bundle:edge`.
const FPE = (() => {
  // ───────────────────────────── src/types.ts ─────────────────────────────
  /**
   * types.ts — L0 type contracts for the Financial Projection Engine.
   *
   * These are pure type declarations (erased at runtime). They describe the
   * shapes the engine consumes and produces. Every runtime (Node, Deno) shares
   * these definitions; the SQL mirror encodes the same shapes as columns.
   *
   * DESIGN INVARIANT: the engine is a projection. Its inputs are only the two
   * immutable financial event streams — paid `contributions` and `withdrawals`.
   * Everything else (wallets) is derived output, never input.
   */

  /** Who absorbs the platform + gateway fees. */
  type FeeBearer = "contributor" | "organizer";

  /**
   * The collection product types. The engine only branches on these for fee
   * rates and normalization; all other product behaviour lives in the callers.
   */
  type CollectionType =
    | "fixed"
    | "fundraising"
    | "tiered"
    | "ticket"
    | "open_pool";

  /**
   * A single paid contribution row — one of the two sources of truth.
   *
   *   amount       = the NET contribution (the organizer's money; NO fees mixed in)
   *   gross_amount = what the contributor actually paid the gateway (net + fees
   *                  when contributor-borne; equal to net when organizer-borne).
   *                  May be absent/0 on legacy rows → falls back to `amount`.
   *   created_at   = ISO timestamp used to classify settled vs pending at cutoff.
   */
  interface ContributionRow {
    amount: number;
    gross_amount?: number | null;
    created_at?: string | null;
    [key: string]: unknown;
  }

  /**
   * A withdrawal row — the second source of truth. Only `amount` and `status`
   * participate in balance math. Status is matched against the canonical
   * COMPLETED / PENDING sets in constants.ts.
   */
  interface WithdrawalRow {
    amount: number;
    status?: string | null;
    [key: string]: unknown;
  }

  /** Output of `calculateFees`. `totalPayable` is what the contributor is charged. */
  interface FeeBreakdown {
    platformFee: number;
    gatewayFee: number;
    totalFees: number;
    totalPayable: number;
  }

  /**
   * The one wallet shape the engine projects. Enforced invariants (asserted in
   * the conformance suite):
   *   - ledger === available + pending
   *   - available >= 0
   *   - withdrawn <= net (a wallet cannot withdraw more than it ever earned net)
   */
  interface WalletProjection {
    /** Σ gross paid (what contributors handed the gateway). */
    gross: number;
    /** Σ net (Total Raised) — organizer money, fees excluded. */
    net: number;
    /** Σ completed/approved withdrawals. */
    withdrawn: number;
    /** Σ net where created_at >= cutoff (not yet settleable). */
    pending: number;
    /** max(0, settledNet − withdrawn) — the withdrawable-eligible settled money. */
    available: number;
    /** available + pending — total funds still in the wallet. */
    ledger: number;
  }

  /**
   * The legacy Node field names (utils/financial.js#computeWalletBalances).
   * Kept as an explicit shape so the Node adapter and the differential parity
   * suite can compare byte-for-byte against today's backend without any mapping
   * ambiguity. `computeWallet` (the canonical output) is a pure relabelling of
   * these same numbers.
   */
  interface WalletBalancesLegacy {
    netPayment: number;
    grossPayment: number;
    pendingBalance: number;
    availableBalance: number;
    ledgerBalance: number;
    completedWithdrawals: number;
  }

  /** Output of `computeCollectionTotals`. */
  interface CollectionTotals {
    /** Σ net contribution amounts (Total Raised). */
    totalContributions: number;
    /** Count of paid contribution rows. */
    count: number;
  }

  /** Output of `computeWithdrawalEligibility` — the strict withdrawable cap. */
  interface WithdrawalEligibility {
    /** available − Σ pending withdrawal requests, floored at 0. */
    withdrawable: number;
    /** Alias of `withdrawable`; the cap the UI and validator compare against. */
    cap: number;
  }

  /** A price tier as stored on a collection (loose shape — passthrough preserved). */
  interface TierInput {
    id?: string | null;
    name?: string | null;
    price?: number | null;
    quantity?: number | null;
    prefix?: string | null;
    description?: string | null;
    [key: string]: unknown;
  }

  /** Output row of `buildTierAvailability` (input tier + sold/remaining stats). */
  interface TierAvailability extends TierInput {
    tierId: string | null;
    tierName: string;
    tierKey: string;
    sold: number;
    totalCapacity: number | null;
    remainingCapacity: number | null;
  }

  // ───────────────────────────── src/constants.ts ─────────────────────────────
  /**
   * constants.ts — L0 canonical financial constants.
   *
   * THE single source for every rate, cap, hour, and status set in Kolekto's
   * money math. Node and Deno import these; the SQL mirror hard-codes the same
   * literals under `-- MIRRORS kolekto-shared-financial` annotation.
   *
   * Lifted verbatim from the reference implementation (kolekto-be-old
   * utils/financial.js), which reconciliation validates at 0 drift. The ONE
   * deliberate convergence: COMPLETED_WITHDRAWAL_STATUSES adopts the Node set
   * (the superset), resolving the latent Node/Edge divergence documented in
   * FINANCIAL_COMPUTATION_MATRIX.md row 15.
   */


  /**
   * Platform fee rate per collection type.
   *   fundraising → 1%; everything else → 0.5%.
   * Unknown types fall back to PLATFORM_FEE_RATE_DEFAULT (see calculateFees).
   */
  const PLATFORM_FEE_RATES: Readonly<Record<CollectionType, number>> = {
    fundraising: 0.01, // 1%
    fixed: 0.005, // 0.5%
    tiered: 0.005, // 0.5%
    ticket: 0.005, // 0.5%
    open_pool: 0.005, // 0.5%
  };

  /** Fallback platform rate for any collection type not in PLATFORM_FEE_RATES. */
  const PLATFORM_FEE_RATE_DEFAULT = 0.005; // 0.5%

  /** Paystack gateway fee rate — 1.5% for all collection types. */
  const GATEWAY_FEE_RATE = 0.015;

  /** Per-fee cap: each of platform and gateway fee is capped at ₦2,000. */
  const MAX_FEE_AMOUNT = 2000;

  /**
   * T+1 settlement hour, in UTC. Settlement runs at 5:00 AM WAT (UTC+1) = 4:00
   * AM UTC. A payment made before the most recent 04:00 UTC cutoff is settled
   * (available); at/after is pending until the next cutoff.
   */
  const SETTLEMENT_HOUR_UTC = 4;

  /** Milliseconds in one day — the cutoff step. */
  const ONE_DAY_MS = 86_400_000;

  /**
   * Withdrawal statuses that count as money that has LEFT the wallet.
   *
   * CANONICAL (superset). Node accepted all four; Edge accepted only
   * {completed, successful}. The engine adopts Node's set — the value
   * reconciliation already validates at 0 drift. Edge conformance to this set is
   * proven by the "approved"/"success" divergence golden vectors.
   *
   *   completed / successful / success → legacy Paystack-transfer terminal states
   *   approved                         → the state the admin panel writes on a
   *                                      manual payout ("mark as paid")
   */
  const COMPLETED_WITHDRAWAL_STATUSES: ReadonlySet<string> = new Set([
    "completed",
    "successful",
    "success",
    "approved",
  ]);

  /**
   * Withdrawal statuses that are in-flight: they reserve against the withdrawable
   * cap but are NOT yet deducted from `available` (only completed withdrawals
   * reduce available). See computeWithdrawalEligibility.
   */
  const PENDING_WITHDRAWAL_STATUSES: ReadonlySet<string> = new Set([
    "pending",
    "processing",
  ]);

  /** All recognised collection types (for validation / iteration). */
  const COLLECTION_TYPES: readonly CollectionType[] = [
    "fixed",
    "fundraising",
    "tiered",
    "ticket",
    "open_pool",
  ];

  /** The two fee bearers. */
  const FEE_BEARERS: readonly FeeBearer[] = ["contributor", "organizer"];

  /**
   * Aggregate constant bag — the shape design docs refer to as `FPE.CONSTANTS`.
   * Prefer the named exports above in new code; this is a convenience view.
   */
  const CONSTANTS = {
    PLATFORM_FEE_RATES,
    PLATFORM_FEE_RATE_DEFAULT,
    GATEWAY_FEE_RATE,
    MAX_FEE_AMOUNT,
    SETTLEMENT_HOUR_UTC,
    ONE_DAY_MS,
    COMPLETED_WITHDRAWAL_STATUSES,
    PENDING_WITHDRAWAL_STATUSES,
    COLLECTION_TYPES,
    FEE_BEARERS,
  } as const;

  // ───────────────────────────── src/primitives.ts ─────────────────────────────
  /**
   * primitives.ts — L1 pure financial primitives.
   *
   * Deterministic, dependency-free building blocks. No I/O, no Supabase, no
   * fetch, no logging. Time enters ONLY through an explicit `now` parameter
   * (defaulting to `new Date()` so existing call sites behave identically) —
   * there is no hidden `Date.now()` inside the math.
   *
   * Every function here is a verbatim lift of the reference implementation
   * (kolekto-be-old/utils/financial.js), except:
   *   - fee rates / cap / cutoff hour come from constants.ts (one source), and
   *   - `getSettlementCutoff` / `isPaymentSettled` accept an injectable `now`.
   * Behaviour is otherwise byte-identical; the differential parity suite proves
   * it against the live backend file.
   */


  // ---------------------------------------------------------------------------
  // roundCurrency
  // ---------------------------------------------------------------------------

  /**
   * Round to 2 decimal places, coercing non-numeric values to 0.
   *
   * The universal money-rounding primitive: every intermediate and final
   * currency value in the engine passes through this so half-up 2dp behaviour is
   * identical everywhere. (`Number.toFixed` is used exactly as the reference
   * does — matching its rounding to the kobo.)
   */
  function roundCurrency(value: unknown): number {
    return Number((Number(value) || 0).toFixed(2));
  }

  // ---------------------------------------------------------------------------
  // Fee rate lookup
  // ---------------------------------------------------------------------------

  /** Platform rate for a collection type, falling back to the default (0.5%). */
  function platformFeeRate(collectionType: string): number {
    return (
      PLATFORM_FEE_RATES[collectionType as CollectionType] ??
      PLATFORM_FEE_RATE_DEFAULT
    );
  }

  // ---------------------------------------------------------------------------
  // calculateFees
  // ---------------------------------------------------------------------------

  /**
   * Calculate the Kolekto platform fee, Paystack gateway fee, and totals.
   *
   * Rules (unchanged from the reference):
   *   - Fees are ALWAYS calculated on the contribution amount, never on payable.
   *   - contributor-borne → totalPayable = amount + totalFees
   *   - organizer-borne   → totalPayable = amount (fees come out of the net share)
   *   - Each fee is capped at MAX_FEE_AMOUNT (₦2,000) independently.
   *   - Fees are NEVER folded into Total Raised / net.
   */
  function calculateFees(
    amount: number,
    collectionType: string = "fixed",
    feeBearer: FeeBearer = "organizer"
  ): FeeBreakdown {
    const sanitizedAmount = roundCurrency(amount);
    const platformRate = platformFeeRate(collectionType);

    const platformFee = roundCurrency(
      Math.min(sanitizedAmount * platformRate, MAX_FEE_AMOUNT)
    );
    const gatewayFee = roundCurrency(
      Math.min(sanitizedAmount * GATEWAY_FEE_RATE, MAX_FEE_AMOUNT)
    );
    const totalFees = roundCurrency(platformFee + gatewayFee);
    const totalPayable =
      feeBearer === "contributor"
        ? roundCurrency(sanitizedAmount + totalFees)
        : sanitizedAmount;

    return { platformFee, gatewayFee, totalFees, totalPayable };
  }

  // ---------------------------------------------------------------------------
  // deriveNetContribution
  // ---------------------------------------------------------------------------

  /**
   * Given the gross amount a contributor paid and the collection settings,
   * derive the NET contribution amount (what the organizer receives).
   *
   * organizer-borne  → gross === net (fees come out of the organizer's share).
   * contributor-borne → gross = net + platformFee + gatewayFee; back it out.
   *   Estimate net = gross / (1 + platformRate + gatewayRate) (exact when
   *   uncapped), then refine once through calculateFees to absorb the ₦2,000
   *   caps. Verbatim lift of the reference (utils/financial.js).
   */
  function deriveNetContribution(
    grossAmount: number,
    collectionType: string = "fixed",
    feeBearer: FeeBearer = "organizer"
  ): number {
    const gross = roundCurrency(grossAmount);
    if (gross <= 0) return 0;

    if (feeBearer === "contributor") {
      const platformRate = platformFeeRate(collectionType);
      const combinedRate = platformRate + GATEWAY_FEE_RATE;

      // Exact when fees are not capped.
      const estimate = roundCurrency(gross / (1 + combinedRate));

      // Refine once to account for the per-fee caps.
      const { totalFees } = calculateFees(estimate, collectionType, "contributor");
      const refined = roundCurrency(gross - totalFees);

      return Math.max(0, refined);
    }

    // Organizer-borne: gross is the contribution amount.
    return gross;
  }

  // ---------------------------------------------------------------------------
  // normalizeContribution(s)
  // ---------------------------------------------------------------------------

  /**
   * Normalize a single contribution row, correcting legacy rows where
   * `gross_amount` is 0/null by deriving the net amount from the gross.
   *
   *   gross === 0 → row passes through untouched (nothing to derive).
   *   otherwise   → amount := net(gross), gross_amount := gross.
   *
   * organizer-borne  → net = gross − totalFees.
   * contributor-borne → net = deriveNetContribution(gross).
   */
  function normalizeContribution<T extends ContributionRow>(
    row: T,
    feeBearer: FeeBearer = "organizer",
    collectionType: string = "fixed"
  ): T {
    const gross = Number(row.gross_amount || row.amount || 0);
    if (gross === 0) return row;

    const { totalFees } = calculateFees(gross, collectionType, feeBearer);
    const net =
      feeBearer === "organizer"
        ? roundCurrency(gross - totalFees)
        : deriveNetContribution(gross, collectionType, feeBearer);

    return {
      ...row,
      amount: net,
      gross_amount: gross,
    };
  }

  /**
   * Array form of `normalizeContribution` — the exact signature the Node backend
   * uses (`normalizeContributions`). Preserved for drop-in delegation in Wave 1.
   */
  function normalizeContributions<T extends ContributionRow>(
    contributions: T[] | null | undefined,
    feeBearer: FeeBearer = "organizer",
    collectionType: string = "fixed"
  ): T[] {
    return (contributions || []).map((row) =>
      normalizeContribution(row, feeBearer, collectionType)
    );
  }

  // ---------------------------------------------------------------------------
  // T+1 settlement
  // ---------------------------------------------------------------------------

  /**
   * The most recent settlement cutoff at or before `now` — SETTLEMENT_HOUR_UTC
   * (04:00) UTC today, or yesterday's if `now` is before today's cutoff.
   *
   * `now` is injectable (defaults to the real clock) so the cutoff is fully
   * deterministic under test and identical across runtimes given the same input.
   */
  function getSettlementCutoff(now: Date = new Date()): Date {
    const todayCutoff = new Date(
      Date.UTC(
        now.getUTCFullYear(),
        now.getUTCMonth(),
        now.getUTCDate(),
        SETTLEMENT_HOUR_UTC,
        0,
        0,
        0
      )
    );

    return now >= todayCutoff
      ? todayCutoff
      : new Date(todayCutoff.getTime() - ONE_DAY_MS);
  }

  /**
   * True if a payment made at `paymentDate` has settled (was made strictly
   * before the most recent cutoff at `now`). At/after the cutoff → pending.
   */
  function isPaymentSettled(
    paymentDate: Date | string,
    now: Date = new Date()
  ): boolean {
    const cutoff = getSettlementCutoff(now);
    return new Date(paymentDate) < cutoff;
  }

  // ---------------------------------------------------------------------------
  // allocateAmounts
  // ---------------------------------------------------------------------------

  /**
   * Split `total` across `weights`, rounding each share to 2dp and giving the
   * remainder to the last item so the parts always sum EXACTLY back to `total`
   * (no rounding leakage). Verbatim lift of the edge implementation
   * (supabase/functions/_shared/payment.ts).
   *
   *   empty weights            → []
   *   total === 0 or Σweight 0 → all-zero array of the same length
   */
  function allocateAmounts(total: number, weights: number[]): number[] {
    const normalizedWeights = weights.map((weight) =>
      roundCurrency(Math.max(0, weight))
    );
    const sum = normalizedWeights.reduce((acc, weight) => acc + weight, 0);

    if (normalizedWeights.length === 0) return [];
    if (roundCurrency(total) === 0 || sum === 0) {
      return normalizedWeights.map(() => 0);
    }

    let remaining = roundCurrency(total);

    return normalizedWeights.map((weight, index) => {
      if (index === normalizedWeights.length - 1) {
        return remaining;
      }
      const share = roundCurrency((total * weight) / sum);
      remaining = roundCurrency(remaining - share);
      return share;
    });
  }

  // ───────────────────────────── src/projections.ts ─────────────────────────────
  /**
   * projections.ts — L2 pure projections.
   *
   * Take arrays of the two source-of-truth streams (paid contributions,
   * withdrawals) and project derived money: wallet balances, organizer roll-ups,
   * collection totals, tier availability, and the withdrawal cap. Pure and
   * deterministic; time enters only via injected `now`.
   *
   * `computeWalletBalances` is a verbatim lift of the reference
   * (kolekto-be-old/utils/financial.js) with the cutoff made injectable and the
   * completed-withdrawal set sourced from constants. `computeWallet` relabels
   * those same numbers into the canonical WalletProjection shape.
   * `buildTierAvailability` is a verbatim lift of the edge implementation.
   */


  // ---------------------------------------------------------------------------
  // Wallet balance projection (the core)
  // ---------------------------------------------------------------------------

  /**
   * Compute the full wallet balance snapshot from raw paid-contribution and
   * withdrawal rows, in the LEGACY Node field names. This is the byte-for-byte
   * reference shape the differential parity suite compares against the live
   * backend. Prefer `computeWallet` (canonical shape) in new code.
   *
   * @param paidContributions rows with { amount, gross_amount?, created_at }
   * @param withdrawals       rows with { amount, status }
   * @param now               injected clock for the settlement cutoff
   */
  function computeWalletBalances(
    paidContributions: ContributionRow[] | null | undefined,
    withdrawals: WithdrawalRow[] | null | undefined,
    now: Date = new Date()
  ): WalletBalancesLegacy {
    const cutoff = getSettlementCutoff(now);
    const rows = paidContributions || [];

    // Total Raised = Σ net contribution amounts (organizer's money).
    const netPayment = roundCurrency(
      rows.reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );

    // Gross = what contributors actually paid (gross_amount, falling back to
    // amount for legacy rows that never populated the column).
    const grossPayment = roundCurrency(
      rows.reduce(
        (sum, row) => sum + Number(row.gross_amount || row.amount || 0),
        0
      )
    );

    // Pending = net from payments made AT/AFTER the last cutoff (not settleable).
    const pendingBalance = roundCurrency(
      rows
        .filter((row) => {
          const ts = row.created_at ? new Date(row.created_at) : null;
          return ts !== null && ts >= cutoff;
        })
        .reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );

    // Settled = net from payments made BEFORE the cutoff.
    const settledNet = roundCurrency(netPayment - pendingBalance);

    // Completed withdrawals (irreversible) — canonical superset status match.
    const completedWithdrawals = roundCurrency(
      (withdrawals || [])
        .filter((row) =>
          COMPLETED_WITHDRAWAL_STATUSES.has(String(row.status || ""))
        )
        .reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );

    // Available = settled net minus what has already left the wallet (floored 0).
    const availableBalance = roundCurrency(
      Math.max(0, settledNet - completedWithdrawals)
    );

    // Ledger = total funds still in the wallet (pending + available).
    const ledgerBalance = roundCurrency(availableBalance + pendingBalance);

    return {
      netPayment,
      grossPayment,
      pendingBalance,
      availableBalance,
      ledgerBalance,
      completedWithdrawals,
    };
  }

  /**
   * Canonical wallet projection. Same numbers as `computeWalletBalances`,
   * relabelled to the engine's WalletProjection shape:
   *   net → net, gross → gross, pending → pending, available → available,
   *   ledger → ledger, completedWithdrawals → withdrawn.
   *
   * Invariants (asserted in the conformance suite):
   *   ledger === available + pending; available >= 0.
   */
  function computeWallet(
    paidContributions: ContributionRow[] | null | undefined,
    withdrawals: WithdrawalRow[] | null | undefined,
    now: Date = new Date()
  ): WalletProjection {
    const b = computeWalletBalances(paidContributions, withdrawals, now);
    return {
      gross: b.grossPayment,
      net: b.netPayment,
      withdrawn: b.completedWithdrawals,
      pending: b.pendingBalance,
      available: b.availableBalance,
      ledger: b.ledgerBalance,
    };
  }

  // ---------------------------------------------------------------------------
  // Balance selectors (over the canonical projection)
  // ---------------------------------------------------------------------------

  /** Settled, withdrawable-eligible balance. */
  function computeAvailableBalance(
    paidContributions: ContributionRow[] | null | undefined,
    withdrawals: WithdrawalRow[] | null | undefined,
    now: Date = new Date()
  ): number {
    return computeWallet(paidContributions, withdrawals, now).available;
  }

  /** Net from payments not yet past the cutoff. */
  function computePendingBalance(
    paidContributions: ContributionRow[] | null | undefined,
    now: Date = new Date()
  ): number {
    return computeWallet(paidContributions, [], now).pending;
  }

  /** available + pending — total funds still in the wallet. */
  function computeLedgerBalance(
    paidContributions: ContributionRow[] | null | undefined,
    withdrawals: WithdrawalRow[] | null | undefined,
    now: Date = new Date()
  ): number {
    return computeWallet(paidContributions, withdrawals, now).ledger;
  }

  /**
   * Sum the `available` across all of an organizer's wallet projections.
   * Accepts anything carrying a numeric `available` (a WalletProjection or a
   * persisted wallet row exposing `available_balance`).
   */
  function computeOrganizerBalance(
    wallets: Array<{ available?: number; available_balance?: number } | null | undefined>
  ): number {
    return roundCurrency(
      (wallets || []).reduce((sum, w) => {
        if (!w) return sum;
        const available = w.available ?? w.available_balance ?? 0;
        return sum + Number(available || 0);
      }, 0)
    );
  }

  // ---------------------------------------------------------------------------
  // Collection totals
  // ---------------------------------------------------------------------------

  /**
   * Total Raised + paid count for a collection. `totalContributions` is Σ net
   * `amount` (matching Total Raised); `count` is the number of paid rows.
   */
  function computeCollectionTotals(
    contributions: ContributionRow[] | null | undefined
  ): CollectionTotals {
    const rows = contributions || [];
    const totalContributions = roundCurrency(
      rows.reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );
    return { totalContributions, count: rows.length };
  }

  // ---------------------------------------------------------------------------
  // Withdrawal eligibility (strict cap)
  // ---------------------------------------------------------------------------

  /** Σ amounts of in-flight (pending/processing) withdrawal requests. */
  function computePendingWithdrawals(
    withdrawals: WithdrawalRow[] | null | undefined,
    { excludeId = null }: { excludeId?: string | number | null } = {}
  ): number {
    return roundCurrency(
      (withdrawals || [])
        .filter((row) => {
          if (excludeId != null && (row as { id?: unknown }).id === excludeId) {
            return false;
          }
          return PENDING_WITHDRAWAL_STATUSES.has(String(row.status || ""));
        })
        .reduce((sum, row) => sum + Number(row.amount || 0), 0)
    );
  }

  /**
   * The strict withdrawable cap: `available − Σ pending withdrawal requests`,
   * floored at 0. Pending requests reserve against the cap but are NOT deducted
   * from `available` (only completed withdrawals reduce available). This is the
   * ONE number the picker and the request validator compare against.
   *
   * @param wallet             a WalletProjection (or any { available } carrier)
   * @param pendingWithdrawals either a pre-summed number, or the raw withdrawal
   *                           rows (they will be summed over PENDING statuses)
   */
  function computeWithdrawalEligibility(
    wallet: { available: number } | Pick<WalletProjection, "available">,
    pendingWithdrawals: number | WithdrawalRow[]
  ): WithdrawalEligibility {
    const pending =
      typeof pendingWithdrawals === "number"
        ? roundCurrency(pendingWithdrawals)
        : computePendingWithdrawals(pendingWithdrawals);

    const cap = roundCurrency(Math.max(0, Number(wallet.available || 0) - pending));
    return { withdrawable: cap, cap };
  }

  // ---------------------------------------------------------------------------
  // Tier availability (verbatim lift of the edge implementation)
  // ---------------------------------------------------------------------------

  function asNumber(value: unknown): number {
    if (typeof value === "number" && Number.isFinite(value)) return value;
    if (typeof value === "string" && value.trim() !== "") {
      const parsed = Number(value.replace(/,/g, ""));
      if (Number.isFinite(parsed)) return parsed;
    }
    return 0;
  }

  function asPositiveInt(value: unknown): number {
    const parsed = Math.floor(asNumber(value));
    return parsed > 0 ? parsed : 0;
  }

  function getTierMatchKey(tier: TierInput, index: number): string {
    return String(tier.id || tier.name || `tier-${index}`);
  }

  function getTierLabel(tier: TierInput, index: number): string {
    return String(tier.name || `Tier ${index + 1}`);
  }

  function getInfoRows(row: Record<string, unknown>): Array<Record<string, unknown>> {
    if (Array.isArray(row.contributor_information)) {
      return row.contributor_information.filter(
        (entry) => entry && typeof entry === "object"
      ) as Array<Record<string, unknown>>;
    }
    if (row.contact_info && typeof row.contact_info === "object") {
      return [row.contact_info as Record<string, unknown>];
    }
    return [];
  }

  /**
   * Compute sold / remaining capacity per price tier from the paid rows.
   * Verbatim lift of supabase/functions/_shared/payment.ts#buildTierAvailability
   * — matches tiers by TierId then Tier name, sums Quantity (default 1).
   */
  function buildTierAvailability(
    tiers: TierInput[],
    paidRows: Array<Record<string, unknown>>
  ): TierAvailability[] {
    const soldByTier = new Map<string, number>();

    for (const row of paidRows) {
      const infoRows = getInfoRows(row);
      for (const info of infoRows) {
        const tierId = info.TierId ? String(info.TierId) : "";
        const tierName = info.Tier ? String(info.Tier) : "";
        const quantity = asPositiveInt(info.Quantity) || 1;

        if (tierId) {
          soldByTier.set(tierId, (soldByTier.get(tierId) || 0) + quantity);
        } else if (tierName) {
          soldByTier.set(tierName, (soldByTier.get(tierName) || 0) + quantity);
        }
      }
    }

    return tiers.map((tier, index) => {
      const tierId = tier.id ? String(tier.id) : null;
      const tierName = getTierLabel(tier, index);
      const sold =
        (tierId ? soldByTier.get(tierId) : undefined) ||
        soldByTier.get(tierName) ||
        0;
      const totalCapacity = tier.quantity == null ? null : asPositiveInt(tier.quantity);
      const remainingCapacity =
        totalCapacity == null ? null : Math.max(0, totalCapacity - sold);

      return {
        ...tier,
        tierId,
        tierName,
        tierKey: getTierMatchKey(tier, index),
        sold,
        totalCapacity,
        remainingCapacity,
      };
    });
  }

  return { roundCurrency, platformFeeRate, calculateFees, deriveNetContribution, normalizeContribution, normalizeContributions, getSettlementCutoff, isPaymentSettled, allocateAmounts, computeWallet, computeWalletBalances, computeAvailableBalance, computePendingBalance, computeLedgerBalance, computeOrganizerBalance, computeCollectionTotals, computePendingWithdrawals, computeWithdrawalEligibility, buildTierAvailability, PLATFORM_FEE_RATES, PLATFORM_FEE_RATE_DEFAULT, GATEWAY_FEE_RATE, MAX_FEE_AMOUNT, SETTLEMENT_HOUR_UTC, ONE_DAY_MS, COMPLETED_WITHDRAWAL_STATUSES, PENDING_WITHDRAWAL_STATUSES, COLLECTION_TYPES, FEE_BEARERS, CONSTANTS };
})();
// <<< FPE-ENGINE-INLINE <<<

// Preserve the previous public API by binding each exported name to the engine.
// These are byte-identical to the removed hand-written versions (proven by the
// package's differential tests) EXCEPT COMPLETED_WITHDRAWAL_STATUSES, which now
// uses the canonical superset {completed, successful, success, approved} — the
// documented Node/SQL convergence that fixes the edge's prior
// {completed, successful} under-count of withdrawn funds.
export const roundCurrency: (value: number) => number = FPE.roundCurrency;
export const calculateFees: (amount: number, collectionType: string, feeBearer: FeeBearer) => { platformFee: number; gatewayFee: number; totalFees: number; totalPayable: number } = FPE.calculateFees;
export const allocateAmounts: (total: number, weights: number[]) => number[] = FPE.allocateAmounts;
export const buildTierAvailability: (tiers: Array<Record<string, unknown>>, paidRows: Array<Record<string, unknown>>) => Array<Record<string, unknown>> = FPE.buildTierAvailability;
export const getSettlementCutoff: (now?: Date) => Date = FPE.getSettlementCutoff;
export const COMPLETED_WITHDRAWAL_STATUSES: ReadonlySet<string> = FPE.COMPLETED_WITHDRAWAL_STATUSES;
export const computeWalletBalances: (
  paidContributions: Array<Record<string, unknown>>,
  withdrawals: Array<Record<string, unknown>>,
  now?: Date
) => { netPayment: number; grossPayment: number; pendingBalance: number; availableBalance: number; ledgerBalance: number; completedWithdrawals: number } = FPE.computeWalletBalances;

export function asNumber(value: unknown): number {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value === "string" && value.trim() !== "") {
    const parsed = Number((value as string).replace(/,/g, ""));
    if (Number.isFinite(parsed)) return parsed;
  }
  return 0;
}

export function asPositiveInt(value: unknown): number {
  const parsed = Math.floor(asNumber(value));
  return parsed > 0 ? parsed : 0;
}

export function getCollectionType(collection: Record<string, unknown>) {
  return String(collection.collection_type || collection.type || "fixed").trim();
}

/**
 * Round 4 correction (verified against real production data): a schema
 * migration added `unique_id_enabled` with `NOT NULL DEFAULT false`, which
 * backfilled EVERY pre-existing collection to `false` — including ones
 * that already had a real `code_prefix` configured and had been
 * generating codes successfully for months under the old (prefix-only)
 * logic. In Kolekto's actual production database this affects 89
 * collections (vs. only 12 with the column genuinely `true`) — treating
 * `false` as a hard block, as an earlier pass here did, silently broke
 * code generation for the large majority of collections that had it
 * working before this column existed, with zero ill effect on the small
 * number of new ones (because the current collection-creation UI always
 * clears `code_prefix` whenever the toggle is off, so for any collection
 * saved through it, "a prefix is configured" and "the toggle is on" are
 * the same fact). So: a configured prefix — collection-level OR on the
 * specific tier/ticket type being purchased — is what actually drives
 * generation; `unique_id_enabled` is read for display only (e.g. whether
 * a receipt shows a "your code" section), never as a gate.
 */
export function hasAnyConfiguredPrefix(collection: Record<string, unknown>): boolean {
  if (collection.code_prefix) return true;
  const tiers = getPriceTiers(collection);
  return tiers.some((t) => Boolean((t as Record<string, unknown>)?.prefix));
}

export function getPriceTiers(collection: Record<string, unknown>) {
  const tiers = collection.price_tiers || collection.pricing_tiers;
  return Array.isArray(tiers) ? tiers : [];
}

// getTierLabel / getTierMatchKey / getInfoRows removed (Wave 4): they were only
// used by the edge's old buildTierAvailability, which now delegates to the engine
// (the engine's inlined copy carries its own equivalents). No other consumer.

// calculateFees is delegated to the engine (bound above). Behaviour is
// byte-identical to the removed edge version across all types × bearers × the
// full amount range (verified in the package's edge-differential tests).

/**
 * Given the total a contributor actually paid (Paystack amount / 100),
 * reverse-calculate the base contribution amount. Used as a fallback when
 * metadata.contributionAmount is missing (e.g. due to Paystack metadata
 * truncation on redirect).
 *
 * INTENTIONALLY NOT DELEGATED to the engine's deriveNetContribution. This
 * binary search and the engine's one-step-refine agree everywhere EXCEPT the
 * partially-fee-capped region (very large contributor-borne payments), where
 * they differ by up to ~₦19.55 — this binary search is actually the more exact
 * inverse. Swapping it would change this rare fallback's output, which is NOT
 * the sanctioned Wave 2 convergence. Left as an edge adapter function pending an
 * explicit decision on the canonical reverse-calc algorithm (see
 * WAVE3_READINESS_REPORT.md, finding R-REV).
 */
export function reverseCalculateContribution(
  totalPayable: number,
  collectionType: string,
  feeBearer: FeeBearer
): number {
  if (feeBearer === "organizer") return roundCurrency(totalPayable);
  // Binary search: find C such that calculateFees(C, ...).totalPayable ≈ totalPayable
  let lo = 0;
  let hi = totalPayable;
  for (let i = 0; i < 60; i++) {
    const mid = (lo + hi) / 2;
    const { totalPayable: tp } = calculateFees(mid, collectionType, feeBearer);
    if (Math.abs(tp - totalPayable) < 0.005) return roundCurrency(mid);
    if (tp < totalPayable) lo = mid;
    else hi = mid;
  }
  return roundCurrency((lo + hi) / 2);
}

// allocateAmounts and buildTierAvailability are delegated to the engine (bound
// above) — verbatim-equivalent to the removed edge versions. asNumber /
// asPositiveInt are retained (used by normalizePaymentRequest / matchTier).

export function matchTier(
  tiers: Array<Record<string, unknown>>,
  selection: Record<string, unknown>
) {
  const requestedTierId = selection.tierId ? String(selection.tierId) : selection.id ? String(selection.id) : null;
  const requestedTierName = selection.tierName ? String(selection.tierName) : selection.name ? String(selection.name) : null;
  return tiers.find((tier) => {
    if (requestedTierId && tier.tierId === requestedTierId) return true;
    if (requestedTierName && tier.tierName === requestedTierName) return true;
    return false;
  }) || null;
}

/**
 * Root-cause fix: this function only ever runs from the `transaction.status
 * === "success"` branch — i.e. AFTER Paystack has already captured the
 * contributor's money. It used to also reject paused/closed/completed/
 * pending_review collections here, which made sense for `initiate-paystack-
 * payment` (blocking a NEW charge attempt) but is wrong here: a collection's
 * CURRENT lifecycle status (which can change between charge-time and
 * verify-time — e.g. an auto-close cron firing on `deadline`, or an admin
 * pausing/closing it) must not retroactively un-confirm a payment Paystack
 * already settled. Doing so silently dropped the contribution (no row, no
 * wallet update, no notification) and was UNRECOVERABLE via Admin Reconcile,
 * because reconcile calls this exact same function/code path and hit the
 * identical rejection every time.
 *
 * Only `deleted_at` remains a hard block — a hard-deleted collection has no
 * wallet/host to credit, so there's nothing safe to do with the money here
 * (requires manual support intervention, not auto-recovery).
 */
export function ensureCollectionIsPayable(collection: Record<string, unknown>, collectionId: string) {
  const status = String(collection.status || "active");
  if (collection.deleted_at) throw new PaymentValidationError("This collection is no longer available.", 404, "collection_deleted", { collectionId, status });
  if (status === "paused" || status === "closed" || status === "completed" || status === "pending_review" || status === "pending_verification") {
    console.warn(
      `[verify] LEGACY_PAYABLE_GATE_BYPASSED collectionId=${collectionId} status=${status} — ` +
      `recording an already-captured Paystack payment despite non-active collection status.`
    );
  }
}

export function normalizePaymentRequest(input: {
  collection: Record<string, unknown>;
  metadata: Record<string, unknown>;
  paidRows?: Array<Record<string, unknown>>;
  paystackVerifiedTotal?: number;
}) {
  const collection = input.collection;
  const metadata = input.metadata || {};
  const paidRows = input.paidRows || [];
  const paystackVerifiedTotal = input.paystackVerifiedTotal ?? 0;

  const collectionId = String(metadata.collectionId || metadata.collection_id || collection.id || "").trim();
  if (!collectionId) throw new PaymentValidationError("A valid collection ID is required.", 400, "missing_collection_id");

  ensureCollectionIsPayable(collection, collectionId);
  const collectionType = getCollectionType(collection);

  // CRITICAL: fundraising fees are ALWAYS contributor-borne.
  // This keeps Total Raised = pure contribution amount across all collection types.
  const feeBearer: FeeBearer =
    collectionType === "fundraising"
      ? "contributor"
      : String(collection.fee_bearer || metadata.feeBearer || "organizer") === "contributor"
      ? "contributor"
      : "organizer";

  // Read both metadata shapes:
  //   NEW (flat): contactName/contactEmail/contactPhone, formDataJson, ticketSelectionsJson
  //   OLD (nested): metadata.contact, metadata.formData, metadata.ticketSelections
  // The new shape was introduced because Paystack rejects deeply-nested
  // metadata with a generic 400 "An error occurred".
  const safeJsonParse = (input: unknown): any => {
    if (input == null) return null;
    if (typeof input === "object") return input;
    if (typeof input === "string") {
      try { return JSON.parse(input); } catch { return null; }
    }
    return null;
  };

  const contactSource = (metadata.contact && typeof metadata.contact === "object")
    ? (metadata.contact as Record<string, unknown>)
    : {
        name: metadata.contactName,
        email: metadata.contactEmail,
        phone: metadata.contactPhone,
      };

  const parsedFormData = safeJsonParse(metadata.formDataJson);
  const formData: Record<string, unknown> =
    (metadata.formData && typeof metadata.formData === "object")
      ? (metadata.formData as Record<string, unknown>)
      : (parsedFormData && typeof parsedFormData === "object")
        ? parsedFormData
        : {};

  const contact = {
    name: String(contactSource.name || "").trim(),
    email: String(contactSource.email || "").trim(),
    phone: String(contactSource.phone || "").trim(),
  };

  const allTiers = buildTierAvailability(getPriceTiers(collection), paidRows);
  const maxContributions = asPositiveInt(collection.max_contributions || collection.max_participants);
  const paidCount = paidRows.length;
  const remainingContributionCapacity = maxContributions > 0 ? Math.max(0, maxContributions - paidCount) : null;

  let contributionAmount = 0;
  let quantity = 1;
  let selectedTier: string | null = null;
  let selectedTierId: string | null = null;
  let selectedTierPrefix: string | null = null;
  let ticketSelections: TicketSelection[] = [];

  if (collectionType === "fundraising" || collectionType === "open_pool") {
    const requestedAmount = roundCurrency(asNumber(metadata.contributionAmount || metadata.amount));
    const minimumAmount = roundCurrency(asNumber(collection.min_contribution || collection.amount));
    // Fallback: if metadata.contributionAmount was lost (e.g. Paystack metadata truncation
    // on redirect), reverse-calculate the base contribution from the verified Paystack total.
    const derivedAmount =
      (!requestedAmount || requestedAmount <= 0) && paystackVerifiedTotal > 0
        ? reverseCalculateContribution(paystackVerifiedTotal, collectionType, feeBearer)
        : 0;
    const effectiveAmount = requestedAmount > 0 ? requestedAmount : derivedAmount;
    if (!effectiveAmount || effectiveAmount <= 0) {
      throw new PaymentValidationError(
        collectionType === "fundraising" ? "Enter a valid donation amount." : "Enter a valid contribution amount.",
        400, "invalid_amount", { collectionId, collectionType, requestedAmount }
      );
    }
    if (minimumAmount > 0 && effectiveAmount < minimumAmount) {
      throw new PaymentValidationError(
        `${collectionType === "fundraising" ? "Minimum donation" : "Minimum contribution"} is NGN ${minimumAmount.toLocaleString("en-NG")}.`,
        400, "amount_below_minimum", { collectionId, effectiveAmount, minimumAmount }
      );
    }
    if (remainingContributionCapacity !== null && remainingContributionCapacity < 1) {
      throw new PaymentValidationError("This collection has reached its contribution limit.", 400, "collection_full", { collectionId, paidCount, maxContributions });
    }
    contributionAmount = effectiveAmount;

  } else if (collectionType === "ticket") {
    if (String(collection.ticket_mode || "") === "tiered") {
      // Accept both nested ticketSelections (legacy) and ticketSelectionsJson (flat).
      const parsedTicketSelections = Array.isArray(metadata.ticketSelections)
        ? (metadata.ticketSelections as Array<Record<string, unknown>>)
        : (() => {
            const parsed = safeJsonParse(metadata.ticketSelectionsJson);
            return Array.isArray(parsed) ? (parsed as Array<Record<string, unknown>>) : [];
          })();
      const rawSelections = parsedTicketSelections;
      const legacyQuantity = asPositiveInt(metadata.quantity) || 1;
      const legacySelection =
        rawSelections.length === 0 && (metadata.selectedTier || metadata.selectedTierId)
          ? [{ tierId: metadata.selectedTierId, tierName: metadata.selectedTier, quantity: legacyQuantity }]
          : rawSelections;

      if (legacySelection.length === 0) {
        throw new PaymentValidationError("Select at least one ticket tier before checkout.", 400, "missing_ticket_selection", { collectionId });
      }

      ticketSelections = legacySelection.map((selection) => {
        const tier = matchTier(allTiers, selection);
        const requestedQuantity = asPositiveInt(selection.quantity);
        if (!tier) throw new PaymentValidationError("One of the selected ticket tiers is no longer available.", 404, "ticket_tier_not_found", { collectionId, selection });
        if (requestedQuantity < 1) return null;
        if (tier.remainingCapacity !== null && requestedQuantity > Number(tier.remainingCapacity)) {
          throw new PaymentValidationError(
            `${tier.tierName} does not have enough tickets left.`,
            400, "insufficient_ticket_capacity",
            { collectionId, tierId: tier.tierId, tierName: tier.tierName, requestedQuantity, remainingCapacity: tier.remainingCapacity }
          );
        }
        return {
          tierId: tier.tierId,
          tierName: String(tier.tierName),
          pricePerUnit: roundCurrency(asNumber(tier.price)),
          quantity: requestedQuantity,
          subtotal: roundCurrency(asNumber(tier.price) * requestedQuantity),
          description: tier.description ? String(tier.description) : null,
          prefix: tier.prefix ? String(tier.prefix) : null,
          remainingCapacity: tier.remainingCapacity as number | null,
        } as TicketSelection;
      }).filter(Boolean) as TicketSelection[];

      quantity = ticketSelections.reduce((t, s) => t + s.quantity, 0);
      if (quantity < 1) throw new PaymentValidationError("Select at least one ticket before checkout.", 400, "missing_ticket_quantity", { collectionId });
      contributionAmount = roundCurrency(ticketSelections.reduce((s, sel) => s + sel.subtotal, 0));

    } else {
      quantity = asPositiveInt(metadata.quantity) || 1;
      if (remainingContributionCapacity !== null && quantity > remainingContributionCapacity) {
        throw new PaymentValidationError("Not enough tickets remain for this order.", 400, "insufficient_ticket_capacity", { collectionId, quantity, remainingContributionCapacity });
      }
      if (String(collection.allow_multiple_quantity) === "false" && quantity > 1) {
        throw new PaymentValidationError("This ticket only allows one purchase per checkout.", 400, "multiple_quantity_disabled", { collectionId, quantity });
      }
      const unitPrice = roundCurrency(asNumber(collection.amount));
      contributionAmount = roundCurrency(unitPrice * quantity);
      ticketSelections = [{
        tierId: null,
        tierName: String(collection.title || "Ticket"),
        pricePerUnit: unitPrice,
        quantity,
        subtotal: contributionAmount,
        prefix: collection.code_prefix ? String(collection.code_prefix) : null,
        remainingCapacity: remainingContributionCapacity,
      }];
    }

  } else if (collectionType === "tiered") {
    let tier = matchTier(allTiers, {
      tierId: metadata.selectedTierId,
      tierName: metadata.selectedTier,
      name: metadata.selectedTier,
    });
    // Recovery fallback: metadata didn't carry an exact tier (e.g. an Admin
    // Reconcile manual override only ever supplies collectionId, never the
    // contributor's original tier choice — that field simply doesn't exist
    // once both pending_payment_context and Paystack's own metadata echo
    // have failed). Infer deterministically from the amount Paystack
    // actually verified: compute every tier's totalPayable the same way
    // initiate did, and auto-select ONLY if exactly one tier matches within
    // a rounding tolerance. Never guess on a tie — same philosophy as
    // attemptDeterministicCollectionRecovery's Strategy E below.
    let tierInferenceAmbiguous = false;
    if (!tier && paystackVerifiedTotal > 0) {
      const amountMatches = allTiers.filter((t) => {
        const tierTotalPayable = calculateFees(asNumber(t.price), collectionType, feeBearer).totalPayable;
        return Math.abs(tierTotalPayable - paystackVerifiedTotal) < 0.5;
      });
      if (amountMatches.length === 1) {
        tier = amountMatches[0];
        console.warn(
          `[verify] TIER_INFERRED_FROM_AMOUNT collectionId=${collectionId} tierId=${tier.tierId} verifiedTotal=${paystackVerifiedTotal}`
        );
      } else if (amountMatches.length > 1) {
        tierInferenceAmbiguous = true;
        console.warn(
          `[verify] TIER_INFERENCE_AMBIGUOUS collectionId=${collectionId} candidates=${amountMatches.length} verifiedTotal=${paystackVerifiedTotal} — refusing to guess`
        );
      }
    }
    if (!tier) {
      throw new PaymentValidationError(
        tierInferenceAmbiguous
          ? "More than one pricing tier matches this payment's amount — supply the tier ID via Admin Reconcile's \"Pricing tier ID\" field."
          : "Select a valid pricing tier before checkout.",
        400, "invalid_selected_tier", { collectionId, selectedTier: metadata.selectedTier }
      );
    }
    if (tier.remainingCapacity !== null && Number(tier.remainingCapacity) < 1) {
      throw new PaymentValidationError(`${tier.tierName} is sold out.`, 400, "tier_sold_out", { collectionId, tierId: tier.tierId, tierName: tier.tierName });
    }
    contributionAmount = roundCurrency(asNumber(tier.price));
    selectedTier = tier.tierName != null ? String(tier.tierName) : null;
    selectedTierId = tier.tierId != null ? String(tier.tierId) : null;
    selectedTierPrefix = tier.prefix ? String(tier.prefix) : null;

  } else {
    // fixed (default)
    if (remainingContributionCapacity !== null && remainingContributionCapacity < 1) {
      throw new PaymentValidationError("This collection has reached its contribution limit.", 400, "collection_full", { collectionId, paidCount, maxContributions });
    }
    contributionAmount = roundCurrency(asNumber(collection.amount));
  }

  if (!contributionAmount || contributionAmount <= 0) {
    throw new PaymentValidationError(
      "Unable to determine a valid payment amount for this checkout.",
      400, "invalid_contribution_amount", { collectionId, collectionType, contributionAmount }
    );
  }

  const feeBreakdown = calculateFees(contributionAmount, collectionType, feeBearer);

  return {
    collectionId,
    collectionType,
    collectionTitle: String(collection.title || "Collection"),
    feeBearer,
    contributionAmount,       // ← stored in contributions.amount → drives Total Raised
    platformFee: feeBreakdown.platformFee,
    gatewayFee: feeBreakdown.gatewayFee,
    totalFees: feeBreakdown.totalFees,
    totalPayable: feeBreakdown.totalPayable,  // ← what Paystack charged
    quantity,
    selectedTier,
    selectedTierId,
    selectedTierPrefix,
    ticketSelections,
    formData,
    contact,
    isAnonymous: metadata.isAnonymous === true || metadata.isAnonymous === 1 || metadata.isAnonymous === "1" || metadata.isAnonymous === "true",
    // Display-only flag now (see hasAnyConfiguredPrefix above) — the
    // actual generation decision is made per-unit, purely from whether a
    // prefix resolves to something non-empty. See CONTRIBUTOR_UNIQUE_ID_FIX_REPORT.md.
    uniqueIdEnabled: hasAnyConfiguredPrefix(collection),
    codePrefix: String(metadata.codePrefix || collection.code_prefix || "").trim(),
    providedAmount: roundCurrency(asNumber(metadata.totalPayable || metadata.amount || 0)),
  };
}

// ─── SETTLEMENT HELPERS ──────────────────────────────────────────────────────
// COMPLETED_WITHDRAWAL_STATUSES and getSettlementCutoff are delegated to the
// engine (bound near the top). The completed-withdrawal set is now the canonical
// superset {completed, successful, success, approved} — previously the edge used
// only {completed, successful}, which under-counted `withdrawn` (and thus
// over-reported `available`) whenever a withdrawal was marked `approved` (the
// admin manual-payout terminal state) or `success`. This is the single
// sanctioned behaviour change in Wave 2; Node and SQL already used this set.

/**
 * Last-resort collectionId recovery when BOTH `pending_payment_context` AND
 * Paystack's own returned metadata come back empty for a reference (seen in
 * production for payments where neither safety net fired — our own insert
 * failed for an unknown transient reason AND Paystack's metadata echo was
 * also empty for the same transaction).
 *
 * Strategy C: another flow may already have tagged this exact
 * payment_reference with a collection_id (e.g. the legacy backend
 * `/payments/initialize-payment` path writes `deposits` rows with
 * collection_id before ever touching Paystack). Reading the SAME reference
 * back is exact-match, zero ambiguity — always safe to trust.
 *
 * Strategy E: ONLY if Strategy C also finds nothing, look for an
 * UNAMBIGUOUS pending checkout — by contributor email + amount + recency —
 * that nothing else has since claimed. This never guesses: any ambiguity
 * (zero or more than one distinct collection) means we return null and the
 * caller falls through to the normal missing-collection-id failure. Wrongly
 * attributing a payment to the wrong organizer's wallet is worse than
 * leaving it for manual admin reconciliation.
 */
export async function attemptDeterministicCollectionRecovery(
  supabase: ReturnType<typeof createClient>,
  params: { reference: string; customerEmail: string; grossAmountPaid: number }
): Promise<{ collectionId: string; strategy: string } | null> {
  const { reference, customerEmail, grossAmountPaid } = params;

  // ── Strategy C: exact payment_reference match in a sibling table ──────────
  // Tier 1: the legacy `deposits` sibling lookup was removed (always empty).
  // `contributions` is the canonical payment_reference source.
  const { data: contributionRow } = await supabase
    .from("contributions")
    .select("collection_id")
    .eq("payment_reference", reference)
    .not("collection_id", "is", null)
    .limit(1)
    .maybeSingle();
  const strategyCMatch =
    (contributionRow as Record<string, unknown> | null)?.collection_id;
  if (strategyCMatch) {
    return { collectionId: String(strategyCMatch), strategy: "strategy_c_reference_match" };
  }

  // ── Strategy E: unambiguous pending-checkout inference ─────────────────────
  if (!customerEmail) return null;
  const cutoffIso = new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString();
  const amountTolerance = Math.max(1, grossAmountPaid * 0.02); // ±2%, min ₦1

  // Tier 1: the legacy `deposits` sibling lookup was removed (always empty).
  const { data: pendingContributions } = await supabase
    .from("contributions")
    .select("collection_id, amount, gross_amount, created_at")
    .ilike("email", customerEmail)
    .eq("status", "pending")
    .is("payment_reference", null)
    .gte("created_at", cutoffIso);

  const candidateCollectionIds = new Set<string>();
  for (const row of (pendingContributions || []) as Array<Record<string, unknown>>) {
    const rowAmount = Number(row.gross_amount || row.amount || 0);
    if (Math.abs(rowAmount - grossAmountPaid) <= amountTolerance && row.collection_id) {
      candidateCollectionIds.add(String(row.collection_id));
    }
  }

  if (candidateCollectionIds.size === 1) {
    return { collectionId: [...candidateCollectionIds][0], strategy: "strategy_e_inferred" };
  }
  if (candidateCollectionIds.size > 1) {
    console.warn(
      `[verify ref=${reference}] STRATEGY_E_AMBIGUOUS candidates=${candidateCollectionIds.size} — refusing to guess`
    );
  }
  return null;
}

// Keys that exist on every contribution regardless of what the host's form
// actually asked — present even when no real answers were ever submitted.
export const STANDARD_INFO_KEYS = new Set([
  "Tier", "TierId", "TierAmount", "Quantity", "_receipt",
  "collectionType", "channel", "paidAt",
]);

export function hasRealAnswers(info: Record<string, unknown> | undefined): boolean {
  if (!info) return false;
  return Object.keys(info).some((k) => !STANDARD_INFO_KEYS.has(k));
}

/**
 * Contributor-info backfill: runs only when a recovered payment's metadata
 * carried NO submitted answers at all (pending_payment_context had no row AND
 * Paystack's own metadata echo was empty) — the exact gap that, in a real
 * incident, left a contribution with only {Tier, TierId, Quantity} on file
 * even though the same contributor's host-form answers (name, phone, custom
 * fields) existed elsewhere in our own database.
 *
 * Looks for an unambiguous prior PAID contribution by the same email in the
 * SAME collection that does carry real answers, and reuses them. Same
 * "never guess" discipline as attemptDeterministicCollectionRecovery's
 * Strategy E: zero or multiple qualifying candidates ⇒ do nothing. Same
 * collection + same email keeps this far less ambiguous than Strategy E's
 * cross-collection amount inference.
 */
export async function attemptContributorInfoBackfill(
  supabase: ReturnType<typeof createClient>,
  params: { reference: string; collectionId: string; email: string }
): Promise<{ contributionId: string; fields: Record<string, unknown>; name: string | null; phone: string | null } | null> {
  const { reference, collectionId, email } = params;
  if (!email) return null;

  const { data: rows, error } = await supabase
    .from("contributions")
    .select("id, name, phone, contributor_information, payment_reference, created_at")
    .eq("collection_id", collectionId)
    .eq("status", "paid")
    .ilike("email", email)
    .neq("payment_reference", reference)
    .order("created_at", { ascending: false })
    .limit(10);

  if (error || !rows) return null;

  const candidates = (rows as Array<Record<string, unknown>>).filter((row) => {
    const infoRows = Array.isArray(row.contributor_information)
      ? (row.contributor_information as Array<Record<string, unknown>>)
      : [];
    return hasRealAnswers(infoRows[0]);
  });

  if (candidates.length !== 1) {
    if (candidates.length > 1) {
      console.warn(
        `[verify ref=${reference}] CONTRIBUTOR_BACKFILL_AMBIGUOUS candidates=${candidates.length} — refusing to guess`
      );
    }
    return null;
  }

  const match = candidates[0];
  const infoRows = Array.isArray(match.contributor_information)
    ? (match.contributor_information as Array<Record<string, unknown>>)
    : [];
  const sourceInfo = infoRows[0] || {};
  const fields = Object.keys(sourceInfo).reduce<Record<string, unknown>>((acc, k) => {
    if (!STANDARD_INFO_KEYS.has(k)) acc[k] = sourceInfo[k];
    return acc;
  }, {});

  if (Object.keys(fields).length === 0) return null;

  return {
    contributionId: String(match.id),
    fields,
    name: match.name ? String(match.name) : null,
    phone: match.phone ? String(match.phone) : null,
  };
}

/**
 * Best-effort, never-throwing diagnostic log into `payment_recovery_log`.
 * Durable visibility into every post-success verify/admin-reconcile outcome
 * — ephemeral console logs vanish once the edge function instance recycles.
 */
export async function logRecoveryAttempt(
  supabase: ReturnType<typeof createClient>,
  entry: {
    reference: string;
    collectionId: string | null;
    success: boolean;
    errorCode?: string | null;
    errorMessage?: string | null;
    metadataSource?: string | null;
    note?: string | null;
    context?: Record<string, unknown> | null;
    // Additive (nullable columns) — populated by the wrapper closure each
    // handler invocation creates (see `logAttempt` near VERIFY_CALLED).
    // Lets the admin dashboard distinguish a frontend-callback verify from
    // a webhook-triggered one from a scheduled-recovery one from a manual
    // admin reconcile, and measure recovery latency, without changing any
    // matching/recovery logic here.
    invocationSource?: string | null;
    attemptNumber?: number | null;
    durationMs?: number | null;
    selectedTierId?: string | null;
  }
) {
  try {
    await supabase.from("payment_recovery_log").insert({
      reference: entry.reference,
      collection_id: entry.collectionId,
      success: entry.success,
      error_code: entry.errorCode ?? null,
      error_message: entry.errorMessage ?? null,
      metadata_source: entry.metadataSource ?? null,
      note: entry.note ?? null,
      context: entry.context ?? null,
      invocation_source: entry.invocationSource ?? null,
      attempt_number: entry.attemptNumber ?? null,
      duration_ms: entry.durationMs ?? null,
      selected_tier_id: entry.selectedTierId ?? null,
    });
  } catch (logErr) {
    console.warn(
      `[verify ref=${entry.reference}] RECOVERY_LOG_WRITE_FAILED (non-fatal):`,
      (logErr as Error)?.message
    );
  }
}

