// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

console.log("Supabase Client Init:");
console.log("URL:", SUPABASE_URL);
console.log("Key Length:", SUPABASE_PUBLISHABLE_KEY?.length);
console.log("Key Start:", SUPABASE_PUBLISHABLE_KEY?.substring(0, 5));

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("VITE_SUPABASE_PUBLISHABLE_KEY is missing/undefined in environment variables!");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: "kolekto-auth-token",
    },
  }
);
